//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.15 at 07:07:47 PM CEST 
//
package org.afnor.medona.v1;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for DataObjectPackageType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataObjectPackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="BinaryDataObject" type="{org:afnor:medona:v1.0}BinaryDataObjectType"/>
 *           &lt;element name="PhysicalDataObject" type="{org:afnor:medona:v1.0}PhysicalDataObjectType"/>
 *         &lt;/choice>
 *         &lt;element name="DescriptiveMetadata" type="{org:afnor:medona:v1.0}DescriptiveMetadataType"/>
 *         &lt;element name="ManagementMetadata" type="{org:afnor:medona:v1.0}ManagementMetadataType"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataObjectPackageType", propOrder = {
    "binaryDataObjectOrPhysicalDataObject",
    "descriptiveMetadata",
    "managementMetadata"
})
public class DataObjectPackageType {

    /**
     * The Binary data object or physical data object.
     */
    @XmlElements({
        @XmlElement(name = "BinaryDataObject", type = BinaryDataObjectType.class),
        @XmlElement(name = "PhysicalDataObject", type = PhysicalDataObjectType.class)
    })
    protected List<DataObjectType> binaryDataObjectOrPhysicalDataObject;
    /**
     * The Descriptive metadata.
     */
    @XmlElement(name = "DescriptiveMetadata", required = true)
    protected DescriptiveMetadataType descriptiveMetadata;
    /**
     * The Management metadata.
     */
    @XmlElement(name = "ManagementMetadata", required = true)
    protected ManagementMetadataType managementMetadata;
    /**
     * The Id.
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the binaryDataObjectOrPhysicalDataObject property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the binaryDataObjectOrPhysicalDataObject property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryDataObjectOrPhysicalDataObject().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null null     {@link BinaryDataObjectType }
     * {@link PhysicalDataObjectType }
     *
     * @return the binary data object or physical data object
     */
    public List<DataObjectType> getBinaryDataObjectOrPhysicalDataObject() {
        if (binaryDataObjectOrPhysicalDataObject == null) {
            binaryDataObjectOrPhysicalDataObject = new ArrayList<DataObjectType>();
        }
        return this.binaryDataObjectOrPhysicalDataObject;
    }

    /**
     * Gets the value of the descriptiveMetadata property.
     *
     * @return possible object is {@link DescriptiveMetadataType }
     */
    public DescriptiveMetadataType getDescriptiveMetadata() {
        return descriptiveMetadata;
    }

    /**
     * Sets the value of the descriptiveMetadata property.
     *
     * @param value allowed object is {@link DescriptiveMetadataType }
     */
    public void setDescriptiveMetadata(DescriptiveMetadataType value) {
        this.descriptiveMetadata = value;
    }

    /**
     * Gets the value of the managementMetadata property.
     *
     * @return possible object is {@link ManagementMetadataType }
     */
    public ManagementMetadataType getManagementMetadata() {
        return managementMetadata;
    }

    /**
     * Sets the value of the managementMetadata property.
     *
     * @param value allowed object is {@link ManagementMetadataType }
     */
    public void setManagementMetadata(ManagementMetadataType value) {
        this.managementMetadata = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
