//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.09.15 at 07:07:47 PM CEST
//
package org.afnor.medona.v1;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import java.math.BigDecimal;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.afnor.medona.v1 package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _DescriptiveMetadata_QNAME =
      new QName("org:afnor:medona:v1.0", "DescriptiveMetadata");
  private static final QName _DataObjectPackage_QNAME =
      new QName("org:afnor:medona:v1.0", "DataObjectPackage");
  private static final QName _Organization_QNAME =
      new QName("org:afnor:medona:v1.0", "Organization");
  private static final QName _ByteSize_QNAME = new QName("org:afnor:medona:v1.0", "ByteSize");
  private static final QName _ManagementMetadata_QNAME =
      new QName("org:afnor:medona:v1.0", "ManagementMetadata");
  private static final QName _MessageDigestBinaryObject_QNAME =
      new QName("org:afnor:medona:v1.0", "MessageDigestBinaryObject");
  private static final QName _PhysicalDataObject_QNAME =
      new QName("org:afnor:medona:v1.0", "PhysicalDataObject");
  private static final QName _OrganizationDescriptiveMetadata_QNAME =
      new QName("org:afnor:medona:v1.0", "OrganizationDescriptiveMetadata");
  private static final QName _Message_QNAME = new QName("org:afnor:medona:v1.0", "Message");
  private static final QName _AuthorizationControlAuthorityRequestReply_QNAME =
      new QName("org:afnor:medona:v1.0", "AuthorizationControlAuthorityRequestReply");
  private static final QName _ArchiveDeliveryRequestReply_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveDeliveryRequestReply");
  private static final QName _ArchiveModificationNotification_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveModificationNotification");
  private static final QName _BinaryDataObject_QNAME =
      new QName("org:afnor:medona:v1.0", "BinaryDataObject");
  private static final QName _Acknowledgement_QNAME =
      new QName("org:afnor:medona:v1.0", "Acknowledgement");
  private static final QName _BinaryObject_QNAME =
      new QName("org:afnor:medona:v1.0", "BinaryObject");
  private static final QName _Text_QNAME = new QName("org:afnor:medona:v1.0", "Text");
  private static final QName _BusinessMessage_QNAME =
      new QName("org:afnor:medona:v1.0", "BusinessMessage");
  private static final QName _ArchiveRestitutionRequestReply_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveRestitutionRequestReply");
  private static final QName _AuthorizationOriginatingAgencyRequest_QNAME =
      new QName("org:afnor:medona:v1.0", "AuthorizationOriginatingAgencyRequest");
  private static final QName _Relationship_QNAME =
      new QName("org:afnor:medona:v1.0", "Relationship");
  private static final QName _Signature_QNAME = new QName("org:afnor:medona:v1.0", "Signature");
  private static final QName _ArchiveRestitutionRequest_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveRestitutionRequest");
  private static final QName _AppraisalRule_QNAME =
      new QName("org:afnor:medona:v1.0", "AppraisalRule");
  private static final QName _ArchiveTransferReply_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveTransferReply");
  private static final QName _BusinessReplyMessage_QNAME =
      new QName("org:afnor:medona:v1.0", "BusinessReplyMessage");
  private static final QName _ArchiveTransfer_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveTransfer");
  private static final QName _ArchiveDestructionNotification_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveDestructionNotification");
  private static final QName _Measure_QNAME = new QName("org:afnor:medona:v1.0", "Measure");
  private static final QName _AccessRule_QNAME = new QName("org:afnor:medona:v1.0", "AccessRule");
  private static final QName _BusinessAuthorizationRequestMessage_QNAME =
      new QName("org:afnor:medona:v1.0", "BusinessAuthorizationRequestMessage");
  private static final QName _AuthorizationControlAuthorityRequest_QNAME =
      new QName("org:afnor:medona:v1.0", "AuthorizationControlAuthorityRequest");
  private static final QName _BusinessRequestMessage_QNAME =
      new QName("org:afnor:medona:v1.0", "BusinessRequestMessage");
  private static final QName _ArchiveTransferRequestReply_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveTransferRequestReply");
  private static final QName _AuthorizationOriginatingAgencyRequestReply_QNAME =
      new QName("org:afnor:medona:v1.0", "AuthorizationOriginatingAgencyRequestReply");
  private static final QName _BusinessNotificationMessage_QNAME =
      new QName("org:afnor:medona:v1.0", "BusinessNotificationMessage");
  private static final QName _DataObject_QNAME = new QName("org:afnor:medona:v1.0", "DataObject");
  private static final QName _AuthorizationRequestContent_QNAME =
      new QName("org:afnor:medona:v1.0", "AuthorizationRequestContent");
  private static final QName _CodeListVersions_QNAME =
      new QName("org:afnor:medona:v1.0", "CodeListVersions");
  private static final QName _BusinessAuthorizationRequestReplyMessage_QNAME =
      new QName("org:afnor:medona:v1.0", "BusinessAuthorizationRequestReplyMessage");
  private static final QName _ArchiveDeliveryRequest_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveDeliveryRequest");
  private static final QName _ArchiveTransferRequest_QNAME =
      new QName("org:afnor:medona:v1.0", "ArchiveTransferRequest");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: org.afnor.medona.v1
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link ManagementMetadataType }
   *
   * @return the management metadata type
   */
  public ManagementMetadataType createManagementMetadataType() {
    return new ManagementMetadataType();
  }

  /**
   * Create an instance of {@link OrganizationType }
   *
   * @return the organization type
   */
  public OrganizationType createOrganizationType() {
    return new OrganizationType();
  }

  /**
   * Create an instance of {@link PhysicalDataObjectType }
   *
   * @return the physical data object type
   */
  public PhysicalDataObjectType createPhysicalDataObjectType() {
    return new PhysicalDataObjectType();
  }

  /**
   * Create an instance of {@link DataObjectType }
   *
   * @return the data object type
   */
  public DataObjectType createDataObjectType() {
    return new DataObjectType();
  }

  /**
   * Create an instance of {@link OrganizationDescriptiveMetadataType }
   *
   * @return the organization descriptive metadata type
   */
  public OrganizationDescriptiveMetadataType createOrganizationDescriptiveMetadataType() {
    return new OrganizationDescriptiveMetadataType();
  }

  /**
   * Create an instance of {@link AuthorizationControlAuthorityRequestReplyType }*
   *
   * @return the authorization control authority request reply type
   */
  public AuthorizationControlAuthorityRequestReplyType
      createAuthorizationControlAuthorityRequestReplyType() {
    return new AuthorizationControlAuthorityRequestReplyType();
  }

  /**
   * Create an instance of {@link ArchiveDestructionNotificationType }
   *
   * @return the archive destruction notification type
   */
  public ArchiveDestructionNotificationType createArchiveDestructionNotificationType() {
    return new ArchiveDestructionNotificationType();
  }

  /**
   * Create an instance of {@link MessageDigestBinaryObjectType }
   *
   * @return the message digest binary object type
   */
  public MessageDigestBinaryObjectType createMessageDigestBinaryObjectType() {
    return new MessageDigestBinaryObjectType();
  }

  /**
   * Create an instance of {@link ArchiveTransferType }
   *
   * @return the archive transfer type
   */
  public ArchiveTransferType createArchiveTransferType() {
    return new ArchiveTransferType();
  }

  /**
   * Create an instance of {@link ArchiveTransferReplyType }
   *
   * @return the archive transfer reply type
   */
  public ArchiveTransferReplyType createArchiveTransferReplyType() {
    return new ArchiveTransferReplyType();
  }

  /**
   * Create an instance of {@link DescriptiveMetadataType }
   *
   * @return the descriptive metadata type
   */
  public DescriptiveMetadataType createDescriptiveMetadataType() {
    return new DescriptiveMetadataType();
  }

  /**
   * Create an instance of {@link DataObjectPackageType }
   *
   * @return the data object package type
   */
  public DataObjectPackageType createDataObjectPackageType() {
    return new DataObjectPackageType();
  }

  /**
   * Create an instance of {@link BinaryDataObjectType }
   *
   * @return the binary data object type
   */
  public BinaryDataObjectType createBinaryDataObjectType() {
    return new BinaryDataObjectType();
  }

  /**
   * Create an instance of {@link AuthorizationControlAuthorityRequestType }
   *
   * @return the authorization control authority request type
   */
  public AuthorizationControlAuthorityRequestType createAuthorizationControlAuthorityRequestType() {
    return new AuthorizationControlAuthorityRequestType();
  }

  /**
   * Create an instance of {@link AcknowledgementType }
   *
   * @return the acknowledgement type
   */
  public AcknowledgementType createAcknowledgementType() {
    return new AcknowledgementType();
  }

  /**
   * Create an instance of {@link BinaryObjectType }
   *
   * @return the binary object type
   */
  public BinaryObjectType createBinaryObjectType() {
    return new BinaryObjectType();
  }

  /**
   * Create an instance of {@link MeasureType }
   *
   * @return the measure type
   */
  public MeasureType createMeasureType() {
    return new MeasureType();
  }

  /**
   * Create an instance of {@link ArchiveDeliveryRequestReplyType }
   *
   * @return the archive delivery request reply type
   */
  public ArchiveDeliveryRequestReplyType createArchiveDeliveryRequestReplyType() {
    return new ArchiveDeliveryRequestReplyType();
  }

  /**
   * Create an instance of {@link AccessRuleType }
   *
   * @return the access rule type
   */
  public AccessRuleType createAccessRuleType() {
    return new AccessRuleType();
  }

  /**
   * Create an instance of {@link ArchiveModificationNotificationType }
   *
   * @return the archive modification notification type
   */
  public ArchiveModificationNotificationType createArchiveModificationNotificationType() {
    return new ArchiveModificationNotificationType();
  }

  /**
   * Create an instance of {@link AuthorizationOriginatingAgencyRequestType }
   *
   * @return the authorization originating agency request type
   */
  public AuthorizationOriginatingAgencyRequestType
      createAuthorizationOriginatingAgencyRequestType() {
    return new AuthorizationOriginatingAgencyRequestType();
  }

  /**
   * Create an instance of {@link TextType }
   *
   * @return the text type
   */
  public TextType createTextType() {
    return new TextType();
  }

  /**
   * Create an instance of {@link ArchiveRestitutionRequestReplyType }
   *
   * @return the archive restitution request reply type
   */
  public ArchiveRestitutionRequestReplyType createArchiveRestitutionRequestReplyType() {
    return new ArchiveRestitutionRequestReplyType();
  }

  /**
   * Create an instance of {@link ArchiveTransferRequestReplyType }
   *
   * @return the archive transfer request reply type
   */
  public ArchiveTransferRequestReplyType createArchiveTransferRequestReplyType() {
    return new ArchiveTransferRequestReplyType();
  }

  /**
   * Create an instance of {@link AuthorizationOriginatingAgencyRequestReplyType }*
   *
   * @return the authorization originating agency request reply type
   */
  public AuthorizationOriginatingAgencyRequestReplyType
      createAuthorizationOriginatingAgencyRequestReplyType() {
    return new AuthorizationOriginatingAgencyRequestReplyType();
  }

  /**
   * Create an instance of {@link CodeListVersionsType }
   *
   * @return the code list versions type
   */
  public CodeListVersionsType createCodeListVersionsType() {
    return new CodeListVersionsType();
  }

  /**
   * Create an instance of {@link AuthorizationRequestContentType }
   *
   * @return the authorization request content type
   */
  public AuthorizationRequestContentType createAuthorizationRequestContentType() {
    return new AuthorizationRequestContentType();
  }

  /**
   * Create an instance of {@link ArchiveDeliveryRequestType }
   *
   * @return the archive delivery request type
   */
  public ArchiveDeliveryRequestType createArchiveDeliveryRequestType() {
    return new ArchiveDeliveryRequestType();
  }

  /**
   * Create an instance of {@link ArchiveRestitutionRequestType }
   *
   * @return the archive restitution request type
   */
  public ArchiveRestitutionRequestType createArchiveRestitutionRequestType() {
    return new ArchiveRestitutionRequestType();
  }

  /**
   * Create an instance of {@link AppraisalRuleType }
   *
   * @return the appraisal rule type
   */
  public AppraisalRuleType createAppraisalRuleType() {
    return new AppraisalRuleType();
  }

  /**
   * Create an instance of {@link ArchiveTransferRequestType }
   *
   * @return the archive transfer request type
   */
  public ArchiveTransferRequestType createArchiveTransferRequestType() {
    return new ArchiveTransferRequestType();
  }

  /**
   * Create an instance of {@link RelationshipType }
   *
   * @return the relationship type
   */
  public RelationshipType createRelationshipType() {
    return new RelationshipType();
  }

  /**
   * Create an instance of {@link SignatureType }
   *
   * @return the signature type
   */
  public SignatureType createSignatureType() {
    return new SignatureType();
  }

  /**
   * Create an instance of {@link IdentifierType }
   *
   * @return the identifier type
   */
  public IdentifierType createIdentifierType() {
    return new IdentifierType();
  }

  /**
   * Create an instance of {@link CodeType }
   *
   * @return the code type
   */
  public CodeType createCodeType() {
    return new CodeType();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "DescriptiveMetadata")
  public JAXBElement<DescriptiveMetadataType> createDescriptiveMetadata(
      DescriptiveMetadataType value) {
    return new JAXBElement<DescriptiveMetadataType>(
        _DescriptiveMetadata_QNAME, DescriptiveMetadataType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectPackageType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "DataObjectPackage")
  public JAXBElement<DataObjectPackageType> createDataObjectPackage(DataObjectPackageType value) {
    return new JAXBElement<DataObjectPackageType>(
        _DataObjectPackage_QNAME, DataObjectPackageType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Organization")
  public JAXBElement<OrganizationType> createOrganization(OrganizationType value) {
    return new JAXBElement<OrganizationType>(
        _Organization_QNAME, OrganizationType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ByteSize")
  public JAXBElement<BigDecimal> createByteSize(BigDecimal value) {
    return new JAXBElement<BigDecimal>(_ByteSize_QNAME, BigDecimal.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ManagementMetadataType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ManagementMetadata")
  public JAXBElement<ManagementMetadataType> createManagementMetadata(
      ManagementMetadataType value) {
    return new JAXBElement<ManagementMetadataType>(
        _ManagementMetadata_QNAME, ManagementMetadataType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link MessageDigestBinaryObjectType }{@code
   * >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "MessageDigestBinaryObject")
  public JAXBElement<MessageDigestBinaryObjectType> createMessageDigestBinaryObject(
      MessageDigestBinaryObjectType value) {
    return new JAXBElement<MessageDigestBinaryObjectType>(
        _MessageDigestBinaryObject_QNAME, MessageDigestBinaryObjectType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link PhysicalDataObjectType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "PhysicalDataObject",
      substitutionHeadNamespace = "org:afnor:medona:v1.0",
      substitutionHeadName = "DataObject")
  public JAXBElement<PhysicalDataObjectType> createPhysicalDataObject(
      PhysicalDataObjectType value) {
    return new JAXBElement<PhysicalDataObjectType>(
        _PhysicalDataObject_QNAME, PhysicalDataObjectType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationDescriptiveMetadataType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "OrganizationDescriptiveMetadata")
  public JAXBElement<OrganizationDescriptiveMetadataType> createOrganizationDescriptiveMetadata(
      OrganizationDescriptiveMetadataType value) {
    return new JAXBElement<OrganizationDescriptiveMetadataType>(
        _OrganizationDescriptiveMetadata_QNAME,
        OrganizationDescriptiveMetadataType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Message")
  public JAXBElement<MessageType> createMessage(MessageType value) {
    return new JAXBElement<MessageType>(_Message_QNAME, MessageType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link
   * AuthorizationControlAuthorityRequestReplyType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "AuthorizationControlAuthorityRequestReply")
  public JAXBElement<AuthorizationControlAuthorityRequestReplyType>
      createAuthorizationControlAuthorityRequestReply(
          AuthorizationControlAuthorityRequestReplyType value) {
    return new JAXBElement<AuthorizationControlAuthorityRequestReplyType>(
        _AuthorizationControlAuthorityRequestReply_QNAME,
        AuthorizationControlAuthorityRequestReplyType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestReplyType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveDeliveryRequestReply")
  public JAXBElement<ArchiveDeliveryRequestReplyType> createArchiveDeliveryRequestReply(
      ArchiveDeliveryRequestReplyType value) {
    return new JAXBElement<ArchiveDeliveryRequestReplyType>(
        _ArchiveDeliveryRequestReply_QNAME, ArchiveDeliveryRequestReplyType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveModificationNotificationType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveModificationNotification")
  public JAXBElement<ArchiveModificationNotificationType> createArchiveModificationNotification(
      ArchiveModificationNotificationType value) {
    return new JAXBElement<ArchiveModificationNotificationType>(
        _ArchiveModificationNotification_QNAME,
        ArchiveModificationNotificationType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BinaryDataObjectType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "BinaryDataObject",
      substitutionHeadNamespace = "org:afnor:medona:v1.0",
      substitutionHeadName = "DataObject")
  public JAXBElement<BinaryDataObjectType> createBinaryDataObject(BinaryDataObjectType value) {
    return new JAXBElement<BinaryDataObjectType>(
        _BinaryDataObject_QNAME, BinaryDataObjectType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgementType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Acknowledgement")
  public JAXBElement<AcknowledgementType> createAcknowledgement(AcknowledgementType value) {
    return new JAXBElement<AcknowledgementType>(
        _Acknowledgement_QNAME, AcknowledgementType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BinaryObjectType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "BinaryObject")
  public JAXBElement<BinaryObjectType> createBinaryObject(BinaryObjectType value) {
    return new JAXBElement<BinaryObjectType>(
        _BinaryObject_QNAME, BinaryObjectType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Text")
  public JAXBElement<TextType> createText(TextType value) {
    return new JAXBElement<TextType>(_Text_QNAME, TextType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BusinessMessageType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "BusinessMessage")
  public JAXBElement<BusinessMessageType> createBusinessMessage(BusinessMessageType value) {
    return new JAXBElement<BusinessMessageType>(
        _BusinessMessage_QNAME, BusinessMessageType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestReplyType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveRestitutionRequestReply")
  public JAXBElement<ArchiveRestitutionRequestReplyType> createArchiveRestitutionRequestReply(
      ArchiveRestitutionRequestReplyType value) {
    return new JAXBElement<ArchiveRestitutionRequestReplyType>(
        _ArchiveRestitutionRequestReply_QNAME,
        ArchiveRestitutionRequestReplyType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link
   * AuthorizationOriginatingAgencyRequestType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "AuthorizationOriginatingAgencyRequest")
  public JAXBElement<AuthorizationOriginatingAgencyRequestType>
      createAuthorizationOriginatingAgencyRequest(AuthorizationOriginatingAgencyRequestType value) {
    return new JAXBElement<AuthorizationOriginatingAgencyRequestType>(
        _AuthorizationOriginatingAgencyRequest_QNAME,
        AuthorizationOriginatingAgencyRequestType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Relationship")
  public JAXBElement<RelationshipType> createRelationship(RelationshipType value) {
    return new JAXBElement<RelationshipType>(
        _Relationship_QNAME, RelationshipType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Signature")
  public JAXBElement<SignatureType> createSignature(SignatureType value) {
    return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestType }{@code
   * >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveRestitutionRequest")
  public JAXBElement<ArchiveRestitutionRequestType> createArchiveRestitutionRequest(
      ArchiveRestitutionRequestType value) {
    return new JAXBElement<ArchiveRestitutionRequestType>(
        _ArchiveRestitutionRequest_QNAME, ArchiveRestitutionRequestType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AppraisalRuleType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "AppraisalRule")
  public JAXBElement<AppraisalRuleType> createAppraisalRule(AppraisalRuleType value) {
    return new JAXBElement<AppraisalRuleType>(
        _AppraisalRule_QNAME, AppraisalRuleType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferReplyType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveTransferReply")
  public JAXBElement<ArchiveTransferReplyType> createArchiveTransferReply(
      ArchiveTransferReplyType value) {
    return new JAXBElement<ArchiveTransferReplyType>(
        _ArchiveTransferReply_QNAME, ArchiveTransferReplyType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BusinessReplyMessageType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "BusinessReplyMessage")
  public JAXBElement<BusinessReplyMessageType> createBusinessReplyMessage(
      BusinessReplyMessageType value) {
    return new JAXBElement<BusinessReplyMessageType>(
        _BusinessReplyMessage_QNAME, BusinessReplyMessageType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveTransfer")
  public JAXBElement<ArchiveTransferType> createArchiveTransfer(ArchiveTransferType value) {
    return new JAXBElement<ArchiveTransferType>(
        _ArchiveTransfer_QNAME, ArchiveTransferType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDestructionNotificationType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveDestructionNotification")
  public JAXBElement<ArchiveDestructionNotificationType> createArchiveDestructionNotification(
      ArchiveDestructionNotificationType value) {
    return new JAXBElement<ArchiveDestructionNotificationType>(
        _ArchiveDestructionNotification_QNAME,
        ArchiveDestructionNotificationType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link MeasureType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "Measure")
  public JAXBElement<MeasureType> createMeasure(MeasureType value) {
    return new JAXBElement<MeasureType>(_Measure_QNAME, MeasureType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AccessRuleType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "AccessRule")
  public JAXBElement<AccessRuleType> createAccessRule(AccessRuleType value) {
    return new JAXBElement<AccessRuleType>(_AccessRule_QNAME, AccessRuleType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link
   * BusinessAuthorizationRequestMessageType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "BusinessAuthorizationRequestMessage")
  public JAXBElement<BusinessAuthorizationRequestMessageType>
      createBusinessAuthorizationRequestMessage(BusinessAuthorizationRequestMessageType value) {
    return new JAXBElement<BusinessAuthorizationRequestMessageType>(
        _BusinessAuthorizationRequestMessage_QNAME,
        BusinessAuthorizationRequestMessageType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link
   * AuthorizationControlAuthorityRequestType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "AuthorizationControlAuthorityRequest")
  public JAXBElement<AuthorizationControlAuthorityRequestType>
      createAuthorizationControlAuthorityRequest(AuthorizationControlAuthorityRequestType value) {
    return new JAXBElement<AuthorizationControlAuthorityRequestType>(
        _AuthorizationControlAuthorityRequest_QNAME,
        AuthorizationControlAuthorityRequestType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BusinessRequestMessageType }{@code
   * >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "BusinessRequestMessage")
  public JAXBElement<BusinessRequestMessageType> createBusinessRequestMessage(
      BusinessRequestMessageType value) {
    return new JAXBElement<BusinessRequestMessageType>(
        _BusinessRequestMessage_QNAME, BusinessRequestMessageType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestReplyType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveTransferRequestReply")
  public JAXBElement<ArchiveTransferRequestReplyType> createArchiveTransferRequestReply(
      ArchiveTransferRequestReplyType value) {
    return new JAXBElement<ArchiveTransferRequestReplyType>(
        _ArchiveTransferRequestReply_QNAME, ArchiveTransferRequestReplyType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link
   * AuthorizationOriginatingAgencyRequestReplyType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "AuthorizationOriginatingAgencyRequestReply")
  public JAXBElement<AuthorizationOriginatingAgencyRequestReplyType>
      createAuthorizationOriginatingAgencyRequestReply(
          AuthorizationOriginatingAgencyRequestReplyType value) {
    return new JAXBElement<AuthorizationOriginatingAgencyRequestReplyType>(
        _AuthorizationOriginatingAgencyRequestReply_QNAME,
        AuthorizationOriginatingAgencyRequestReplyType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BusinessNotificationMessageType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "BusinessNotificationMessage")
  public JAXBElement<BusinessNotificationMessageType> createBusinessNotificationMessage(
      BusinessNotificationMessageType value) {
    return new JAXBElement<BusinessNotificationMessageType>(
        _BusinessNotificationMessage_QNAME, BusinessNotificationMessageType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "DataObject")
  public JAXBElement<DataObjectType> createDataObject(DataObjectType value) {
    return new JAXBElement<DataObjectType>(_DataObject_QNAME, DataObjectType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationRequestContentType
   * }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "AuthorizationRequestContent")
  public JAXBElement<AuthorizationRequestContentType> createAuthorizationRequestContent(
      AuthorizationRequestContentType value) {
    return new JAXBElement<AuthorizationRequestContentType>(
        _AuthorizationRequestContent_QNAME, AuthorizationRequestContentType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link CodeListVersionsType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "CodeListVersions")
  public JAXBElement<CodeListVersionsType> createCodeListVersions(CodeListVersionsType value) {
    return new JAXBElement<CodeListVersionsType>(
        _CodeListVersions_QNAME, CodeListVersionsType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link
   * BusinessAuthorizationRequestReplyMessageType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:afnor:medona:v1.0",
      name = "BusinessAuthorizationRequestReplyMessage")
  public JAXBElement<BusinessAuthorizationRequestReplyMessageType>
      createBusinessAuthorizationRequestReplyMessage(
          BusinessAuthorizationRequestReplyMessageType value) {
    return new JAXBElement<BusinessAuthorizationRequestReplyMessageType>(
        _BusinessAuthorizationRequestReplyMessage_QNAME,
        BusinessAuthorizationRequestReplyMessageType.class,
        null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestType }{@code
   * >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveDeliveryRequest")
  public JAXBElement<ArchiveDeliveryRequestType> createArchiveDeliveryRequest(
      ArchiveDeliveryRequestType value) {
    return new JAXBElement<ArchiveDeliveryRequestType>(
        _ArchiveDeliveryRequest_QNAME, ArchiveDeliveryRequestType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestType }{@code
   * >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:afnor:medona:v1.0", name = "ArchiveTransferRequest")
  public JAXBElement<ArchiveTransferRequestType> createArchiveTransferRequest(
      ArchiveTransferRequestType value) {
    return new JAXBElement<ArchiveTransferRequestType>(
        _ArchiveTransferRequest_QNAME, ArchiveTransferRequestType.class, null, value);
  }
}
