//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.15 at 07:07:47 PM CEST 
//
package org.afnor.medona.v1;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for OrganizationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrganizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifier" type="{org:afnor:medona:v1.0}IdentifierType"/>
 *         &lt;element name="OrganizationDescriptiveMetadata" type="{org:afnor:medona:v1.0}OrganizationDescriptiveMetadataType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationType", propOrder = {
    "identifier",
    "organizationDescriptiveMetadata"
})
public class OrganizationType {

    /**
     * The Identifier.
     */
    @XmlElement(name = "Identifier", required = true)
    protected IdentifierType identifier;
    /**
     * The Organization descriptive metadata.
     */
    @XmlElement(name = "OrganizationDescriptiveMetadata")
    protected OrganizationDescriptiveMetadataType organizationDescriptiveMetadata;
    /**
     * The Id.
     */
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is {@link IdentifierType }
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is {@link IdentifierType }
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the organizationDescriptiveMetadata property.
     *
     * @return possible object is {@link OrganizationDescriptiveMetadataType }
     */
    public OrganizationDescriptiveMetadataType getOrganizationDescriptiveMetadata() {
        return organizationDescriptiveMetadata;
    }

    /**
     * Sets the value of the organizationDescriptiveMetadata property.
     *
     * @param value allowed object is {@link OrganizationDescriptiveMetadataType
     *              }
     */
    public void setOrganizationDescriptiveMetadata(OrganizationDescriptiveMetadataType value) {
        this.organizationDescriptiveMetadata = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
