//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v21;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CustodialHistoryItemType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustodialHistoryItemType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;fr:gouv:culture:archivesdefrance:seda:v2.1>TextType">
 *       &lt;attribute name="when" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DateType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustodialHistoryItemType")
public class CustodialHistoryItemType
        extends TextType {

    /**
     * The When.
     */
    @XmlAttribute(name = "when")
    protected String when;

    /**
     * Gets the value of the when property.
     *
     * @return possible object is {@link String }
     */
    public String getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     *
     * @param value allowed object is {@link String }
     */
    public void setWhen(String value) {
        this.when = value;
    }

}
