//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v21;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for DataObjectOrArchiveUnitReferenceType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataObjectOrArchiveUnitReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ArchiveUnitRefId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitRefIdType"/>
 *         &lt;element name="DataObjectReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefType"/>
 *         &lt;element name="RepositoryArchiveUnitPID" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType"/>
 *         &lt;element name="RepositoryObjectPID" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType"/>
 *         &lt;element name="ExternalReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataObjectOrArchiveUnitReferenceType", propOrder = {
    "archiveUnitRefId",
    "dataObjectReference",
    "repositoryArchiveUnitPID",
    "repositoryObjectPID",
    "externalReference"
})
public class DataObjectOrArchiveUnitReferenceType {

    /**
     * The Archive unit ref id.
     */
    @XmlElement(name = "ArchiveUnitRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object archiveUnitRefId;
    /**
     * The Data object reference.
     */
    @XmlElement(name = "DataObjectReference")
    protected DataObjectRefType dataObjectReference;
    /**
     * The Repository archive unit pid.
     */
    @XmlElement(name = "RepositoryArchiveUnitPID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String repositoryArchiveUnitPID;
    /**
     * The Repository object pid.
     */
    @XmlElement(name = "RepositoryObjectPID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String repositoryObjectPID;
    /**
     * The External reference.
     */
    @XmlElement(name = "ExternalReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String externalReference;

    /**
     * Gets the value of the archiveUnitRefId property.
     *
     * @return possible object is {@link Object }
     */
    public Object getArchiveUnitRefId() {
        return archiveUnitRefId;
    }

    /**
     * Sets the value of the archiveUnitRefId property.
     *
     * @param value allowed object is {@link Object }
     */
    public void setArchiveUnitRefId(Object value) {
        this.archiveUnitRefId = value;
    }

    /**
     * Gets the value of the dataObjectReference property.
     *
     * @return possible object is {@link DataObjectRefType }
     */
    public DataObjectRefType getDataObjectReference() {
        return dataObjectReference;
    }

    /**
     * Sets the value of the dataObjectReference property.
     *
     * @param value allowed object is {@link DataObjectRefType }
     */
    public void setDataObjectReference(DataObjectRefType value) {
        this.dataObjectReference = value;
    }

    /**
     * Gets the value of the repositoryArchiveUnitPID property.
     *
     * @return possible object is {@link String }
     */
    public String getRepositoryArchiveUnitPID() {
        return repositoryArchiveUnitPID;
    }

    /**
     * Sets the value of the repositoryArchiveUnitPID property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRepositoryArchiveUnitPID(String value) {
        this.repositoryArchiveUnitPID = value;
    }

    /**
     * Gets the value of the repositoryObjectPID property.
     *
     * @return possible object is {@link String }
     */
    public String getRepositoryObjectPID() {
        return repositoryObjectPID;
    }

    /**
     * Sets the value of the repositoryObjectPID property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRepositoryObjectPID(String value) {
        this.repositoryObjectPID = value;
    }

    /**
     * Gets the value of the externalReference property.
     *
     * @return possible object is {@link String }
     */
    public String getExternalReference() {
        return externalReference;
    }

    /**
     * Sets the value of the externalReference property.
     *
     * @param value allowed object is {@link String }
     */
    public void setExternalReference(String value) {
        this.externalReference = value;
    }

}
