//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.10.29 at 01:17:12 AM CET
//
package fr.gouv.culture.archivesdefrance.seda.v21;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Référence à un objet-données ou à un groupe d'objets-données.
 *
 * <p>Java class for DataObjectRefType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataObjectRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="DataObjectReferenceId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefIdType"/>
 *           &lt;element name="DataObjectGroupReferenceId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}GroupRefIdType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "DataObjectRefType",
    propOrder = {"dataObjectReferenceId", "dataObjectGroupReferenceId"})
public class DataObjectRefType {

  /** The Data object reference id. */
  @XmlElement(name = "DataObjectReferenceId")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object dataObjectReferenceId;

  /** The Data object group reference id. */
  @XmlElement(name = "DataObjectGroupReferenceId")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object dataObjectGroupReferenceId;

  /** The Id. */
  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  /**
   * Gets the value of the dataObjectReferenceId property.
   *
   * @return possible object is {@link Object }
   */
  public Object getDataObjectReferenceId() {
    return dataObjectReferenceId;
  }

  /**
   * Sets the value of the dataObjectReferenceId property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setDataObjectReferenceId(Object value) {
    this.dataObjectReferenceId = value;
  }

  /**
   * Gets the value of the dataObjectGroupReferenceId property.
   *
   * @return possible object is {@link Object }
   */
  public Object getDataObjectGroupReferenceId() {
    return dataObjectGroupReferenceId;
  }

  /**
   * Sets the value of the dataObjectGroupReferenceId property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setDataObjectGroupReferenceId(Object value) {
    this.dataObjectGroupReferenceId = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }
}
