//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v21;

import jakarta.xml.bind.annotation.*;

/**
 * <p>
 * Java class for EventLogBookOgType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EventLogBookOgType">
 *   &lt;complexContent>
 *     &lt;extension base="{fr:gouv:culture:archivesdefrance:seda:v2.1}EventType">
 *       &lt;sequence>
 *         &lt;element name="DataObjectReferenceId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventLogBookOgType", propOrder = {
    "dataObjectReferenceId"
})
public class EventLogBookOgType
        extends EventType {

    /**
     * The Data object reference id.
     */
    @XmlElement(name = "DataObjectReferenceId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object dataObjectReferenceId;

    /**
     * Gets the value of the dataObjectReferenceId property.
     *
     * @return possible object is {@link Object }
     */
    public Object getDataObjectReferenceId() {
        return dataObjectReferenceId;
    }

    /**
     * Sets the value of the dataObjectReferenceId property.
     *
     * @param value allowed object is {@link Object }
     */
    public void setDataObjectReferenceId(Object value) {
        this.dataObjectReferenceId = value;
    }

}
