//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.10.29 at 01:17:12 AM CET
//
package fr.gouv.culture.archivesdefrance.seda.v21;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Référence à un objet-données ou à un groupe d'objets-données existant.
 *
 * <p>Java class for ManagementHistoryDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ManagementHistoryDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Management" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ManagementType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ManagementHistoryDataType",
    propOrder = {"version", "management"})
public class ManagementHistoryDataType {

  /** The Version. */
  @XmlElement(name = "Version", required = true)
  protected String version;

  /** The Management. */
  @XmlElement(name = "Management")
  protected ManagementType management;

  /**
   * Gets the value of the version property.
   *
   * @return possible object is {@link String }
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   *
   * @param value allowed object is {@link String }
   */
  public void setVersion(String value) {
    this.version = value;
  }

  /**
   * Gets the value of the management property.
   *
   * @return possible object is {@link ManagementType }
   */
  public ManagementType getManagement() {
    return management;
  }

  /**
   * Sets the value of the management property.
   *
   * @param value allowed object is {@link ManagementType }
   */
  public void setManagement(ManagementType value) {
    this.management = value;
  }
}
