//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.15 at 07:07:47 PM CEST 
//
package org.fntc.ta.v4;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for EventType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventIdentifier" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="EventTypeCode" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="EventType" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="EventDateTime" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="EventDetail" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="Outcome" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="OutcomeDetail" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="OutcomeDetailMessage" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *         &lt;element name="EventDetailData" type="{org:fntc:ta:v4.0}TextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "eventIdentifier",
    "eventTypeCode",
    "eventType",
    "eventDateTime",
    "eventDetail",
    "outcome",
    "outcomeDetail",
    "outcomeDetailMessage",
    "eventDetailData"
})
public class EventType {

    /**
     * The Event identifier.
     */
    @XmlElement(name = "EventIdentifier")
    protected TextType eventIdentifier;
    /**
     * The Event type code.
     */
    @XmlElement(name = "EventTypeCode")
    protected TextType eventTypeCode;
    /**
     * The Event type.
     */
    @XmlElement(name = "EventType")
    protected TextType eventType;
    /**
     * The Event date time.
     */
    @XmlElement(name = "EventDateTime", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar eventDateTime;
    /**
     * The Event detail.
     */
    @XmlElement(name = "EventDetail")
    protected TextType eventDetail;
    /**
     * The Outcome.
     */
    @XmlElement(name = "Outcome")
    protected TextType outcome;
    /**
     * The Outcome detail.
     */
    @XmlElement(name = "OutcomeDetail")
    protected TextType outcomeDetail;
    /**
     * The Outcome detail message.
     */
    @XmlElement(name = "OutcomeDetailMessage")
    protected TextType outcomeDetailMessage;
    /**
     * The Event detail data.
     */
    @XmlElement(name = "EventDetailData")
    protected TextType eventDetailData;

    /**
     * Gets the value of the eventIdentifier property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getEventIdentifier() {
        return eventIdentifier;
    }

    /**
     * Sets the value of the eventIdentifier property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setEventIdentifier(TextType value) {
        this.eventIdentifier = value;
    }

    /**
     * Gets the value of the eventTypeCode property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getEventTypeCode() {
        return eventTypeCode;
    }

    /**
     * Sets the value of the eventTypeCode property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setEventTypeCode(TextType value) {
        this.eventTypeCode = value;
    }

    /**
     * Gets the value of the eventType property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setEventType(TextType value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the eventDateTime property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEventDateTime() {
        return eventDateTime;
    }

    /**
     * Sets the value of the eventDateTime property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     */
    public void setEventDateTime(XMLGregorianCalendar value) {
        this.eventDateTime = value;
    }

    /**
     * Gets the value of the eventDetail property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getEventDetail() {
        return eventDetail;
    }

    /**
     * Sets the value of the eventDetail property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setEventDetail(TextType value) {
        this.eventDetail = value;
    }

    /**
     * Gets the value of the outcome property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getOutcome() {
        return outcome;
    }

    /**
     * Sets the value of the outcome property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setOutcome(TextType value) {
        this.outcome = value;
    }

    /**
     * Gets the value of the outcomeDetail property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getOutcomeDetail() {
        return outcomeDetail;
    }

    /**
     * Sets the value of the outcomeDetail property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setOutcomeDetail(TextType value) {
        this.outcomeDetail = value;
    }

    /**
     * Gets the value of the outcomeDetailMessage property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getOutcomeDetailMessage() {
        return outcomeDetailMessage;
    }

    /**
     * Sets the value of the outcomeDetailMessage property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setOutcomeDetailMessage(TextType value) {
        this.outcomeDetailMessage = value;
    }

    /**
     * Gets the value of the eventDetailData property.
     *
     * @return possible object is {@link TextType }
     */
    public TextType getEventDetailData() {
        return eventDetailData;
    }

    /**
     * Sets the value of the eventDetailData property.
     *
     * @param value allowed object is {@link TextType }
     */
    public void setEventDetailData(TextType value) {
        this.eventDetailData = value;
    }

}
