//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.09.15 at 07:07:47 PM CEST
//
package org.fntc.ta.v4;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.fntc.ta.v4 package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _ArchiveUnits_QNAME = new QName("org:fntc:ta:v4.0", "ArchiveUnits");
  private static final QName _Name_QNAME = new QName("org:fntc:ta:v4.0", "Name");
  private static final QName _AccessRule_QNAME = new QName("org:fntc:ta:v4.0", "AccessRule");
  private static final QName _Text_QNAME = new QName("org:fntc:ta:v4.0", "Text");
  private static final QName _AppraisalRule_QNAME = new QName("org:fntc:ta:v4.0", "AppraisalRule");
  private static final QName _Format_QNAME = new QName("org:fntc:ta:v4.0", "Format");
  private static final QName _ArchiveUnitTypeDataObjectReferenceDataObjectReferenceId_QNAME =
      new QName("org:fntc:ta:v4.0", "DataObjectReferenceId");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: org.fntc.ta.v4
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link ArchiveUnitType }
   *
   * @return the archive unit type
   */
  public ArchiveUnitType createArchiveUnitType() {
    return new ArchiveUnitType();
  }

  /**
   * Create an instance of {@link ArchiveUnitsType }
   *
   * @return the archive units type
   */
  public ArchiveUnitsType createArchiveUnitsType() {
    return new ArchiveUnitsType();
  }

  /**
   * Create an instance of {@link TextType }
   *
   * @return the text type
   */
  public TextType createTextType() {
    return new TextType();
  }

  /**
   * Create an instance of {@link AppraisalRuleType }
   *
   * @return the appraisal rule type
   */
  public AppraisalRuleType createAppraisalRuleType() {
    return new AppraisalRuleType();
  }

  /**
   * Create an instance of {@link AccessRuleType }
   *
   * @return the access rule type
   */
  public AccessRuleType createAccessRuleType() {
    return new AccessRuleType();
  }

  /**
   * Create an instance of {@link ManagementType }
   *
   * @return the management type
   */
  public ManagementType createManagementType() {
    return new ManagementType();
  }

  /**
   * Create an instance of {@link EventType }
   *
   * @return the event type
   */
  public EventType createEventType() {
    return new EventType();
  }

  /**
   * Create an instance of {@link TagType }
   *
   * @return the tag type
   */
  public TagType createTagType() {
    return new TagType();
  }

  /**
   * Create an instance of {@link LogBookType }
   *
   * @return the log book type
   */
  public LogBookType createLogBookType() {
    return new LogBookType();
  }

  /**
   * Create an instance of {@link ExtendedType }
   *
   * @return the extended type
   */
  public ExtendedType createExtendedType() {
    return new ExtendedType();
  }

  /**
   * Create an instance of {@link DescriptiveMetadataContentType }
   *
   * @return the descriptive metadata content type
   */
  public DescriptiveMetadataContentType createDescriptiveMetadataContentType() {
    return new DescriptiveMetadataContentType();
  }

  /**
   * Create an instance of {@link ArchiveUnitType.DataObjectReference }
   *
   * @return the archive unit type . data object reference
   */
  public ArchiveUnitType.DataObjectReference createArchiveUnitTypeDataObjectReference() {
    return new ArchiveUnitType.DataObjectReference();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveUnitsType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:fntc:ta:v4.0", name = "ArchiveUnits")
  public JAXBElement<ArchiveUnitsType> createArchiveUnits(ArchiveUnitsType value) {
    return new JAXBElement<ArchiveUnitsType>(
        _ArchiveUnits_QNAME, ArchiveUnitsType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:fntc:ta:v4.0", name = "Name")
  public JAXBElement<TextType> createName(TextType value) {
    return new JAXBElement<TextType>(_Name_QNAME, TextType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AccessRuleType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:fntc:ta:v4.0", name = "AccessRule")
  public JAXBElement<AccessRuleType> createAccessRule(AccessRuleType value) {
    return new JAXBElement<AccessRuleType>(_AccessRule_QNAME, AccessRuleType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:fntc:ta:v4.0", name = "Text")
  public JAXBElement<TextType> createText(TextType value) {
    return new JAXBElement<TextType>(_Text_QNAME, TextType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AppraisalRuleType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:fntc:ta:v4.0", name = "AppraisalRule")
  public JAXBElement<AppraisalRuleType> createAppraisalRule(AppraisalRuleType value) {
    return new JAXBElement<AppraisalRuleType>(
        _AppraisalRule_QNAME, AppraisalRuleType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(namespace = "org:fntc:ta:v4.0", name = "Format")
  public JAXBElement<TextType> createFormat(TextType value) {
    return new JAXBElement<TextType>(_Format_QNAME, TextType.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
   *
   * @param value the value
   * @return the jaxb element
   */
  @XmlElementDecl(
      namespace = "org:fntc:ta:v4.0",
      name = "DataObjectReferenceId",
      scope = ArchiveUnitType.DataObjectReference.class)
  @XmlIDREF
  public JAXBElement<Object> createArchiveUnitTypeDataObjectReferenceDataObjectReferenceId(
      Object value) {
    return new JAXBElement<Object>(
        _ArchiveUnitTypeDataObjectReferenceDataObjectReferenceId_QNAME,
        Object.class,
        ArchiveUnitType.DataObjectReference.class,
        value);
  }
}
