//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

import java.util.ArrayList;
import java.util.List;

/**
 * Unité de base des métadonnées de description contenant la gestion de l'arborescence.
 *
 * <p>
 * Java class for ArchiveUnitType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ArchiveUnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ArchiveUnitRefId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitRefIdType"/>
 *         &lt;sequence>
 *           &lt;element name="ArchiveUnitProfile" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType" minOccurs="0"/>
 *           &lt;element name="Management" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ManagementType" minOccurs="0"/>
 *           &lt;element name="Content" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DescriptiveMetadataContentType"/>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element name="ArchiveUnit" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitType"/>
 *             &lt;element name="DataObjectReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefType"/>
 *             &lt;element name="DataObjectGroup" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ObjectGroupRefType"/>
 *             &lt;any processContents='lax' minOccurs="0"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArchiveUnitType", propOrder = {
    "archiveUnitRefId",
    "archiveUnitProfile",
    "management",
    "content",
    "archiveUnitOrDataObjectReferenceOrDataObjectGroup"
})
public class ArchiveUnitType {

    /**
     * The Archive unit ref id.
     */
    @XmlElement(name = "ArchiveUnitRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object archiveUnitRefId;
    /**
     * The Archive unit profile.
     */
    @XmlElement(name = "ArchiveUnitProfile")
    protected IdentifierType archiveUnitProfile;
    /**
     * The Management.
     */
    @XmlElement(name = "Management")
    protected ManagementType management;
    /**
     * The Content.
     */
    @XmlElement(name = "Content")
    protected DescriptiveMetadataContentType content;

    /**
     * The Archive unit or data object reference or data object group.
     */
// $ed
//    @XmlElementRefs({
//        @XmlElementRef(name = "ArchiveUnit", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
//        @XmlElementRef(name = "DataObjectReference", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
//        @XmlElementRef(name = "DataObjectGroup", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false)
//    })
//    @XmlAnyElement(lax = true)
    @XmlElements({
        @XmlElement(name = "ArchiveUnit", type = ArchiveUnitType.class),
        @XmlElement(name = "DataObjectReference", type = DataObjectRefType.class),
        @XmlElement(name = "DataObjectGroup", type = DataObjectGroupType.class)
    })
    protected List<Object> archiveUnitOrDataObjectReferenceOrDataObjectGroup;
    /**
     * The Id.
     */
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the archiveUnitRefId property.
     *
     * @return possible object is {@link Object }
     */
    public Object getArchiveUnitRefId() {
        return archiveUnitRefId;
    }

    /**
     * Sets the value of the archiveUnitRefId property.
     *
     * @param value allowed object is {@link Object }
     */
    public void setArchiveUnitRefId(Object value) {
        this.archiveUnitRefId = value;
    }

    /**
     * Gets the value of the archiveUnitProfile property.
     *
     * @return possible object is {@link IdentifierType }
     */
    public IdentifierType getArchiveUnitProfile() {
        return archiveUnitProfile;
    }

    /**
     * Sets the value of the archiveUnitProfile property.
     *
     * @param value allowed object is {@link IdentifierType }
     */
    public void setArchiveUnitProfile(IdentifierType value) {
        this.archiveUnitProfile = value;
    }

    /**
     * Gets the value of the management property.
     *
     * @return possible object is {@link ManagementType }
     */
    public ManagementType getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     *
     * @param value allowed object is {@link ManagementType }
     */
    public void setManagement(ManagementType value) {
        this.management = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return possible object is {@link DescriptiveMetadataContentType }
     */
    public DescriptiveMetadataContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value allowed object is {@link DescriptiveMetadataContentType }
     */
    public void setContent(DescriptiveMetadataContentType value) {
        this.content = value;
    }

    /**
     * Gets the value of the archiveUnitOrDataObjectReferenceOrDataObjectGroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the archiveUnitOrDataObjectReferenceOrDataObjectGroup property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchiveUnitOrDataObjectReferenceOrDataObjectGroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null null     {@link JAXBElement }{@code <}{@link ArchiveUnitType }{@code >}
     * {@link JAXBElement }{@code <}{@link DataObjectRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link ObjectGroupRefType }{@code >}
     * {@link Element }
     * {@link Object }
     *
     * @return the archive unit or data object reference or data object group
     */
    public List<Object> getArchiveUnitOrDataObjectReferenceOrDataObjectGroup() {
        if (archiveUnitOrDataObjectReferenceOrDataObjectGroup == null) {
            archiveUnitOrDataObjectReferenceOrDataObjectGroup = new ArrayList<Object>();
        }
        return this.archiveUnitOrDataObjectReferenceOrDataObjectGroup;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
