//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * Unité de base des métadonnées de description contenant la gestion de l'arborescence.
 * 
 * <p>Java class for ArchiveUnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ArchiveUnitType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="ArchiveUnitRefId" type="{fr:gouv:culture:archivesdefrance:seda:v2}ArchiveUnitRefIdType"/>
 *         <sequence>
 *           <element name="ArchiveUnitProfile" type="{fr:gouv:culture:archivesdefrance:seda:v2}IdentifierType" minOccurs="0"/>
 *           <element name="Management" type="{fr:gouv:culture:archivesdefrance:seda:v2}ManagementType" minOccurs="0"/>
 *           <element name="Content" type="{fr:gouv:culture:archivesdefrance:seda:v2}DescriptiveMetadataContentType"/>
 *           <choice maxOccurs="unbounded" minOccurs="0">
 *             <element name="ArchiveUnit" type="{fr:gouv:culture:archivesdefrance:seda:v2}ArchiveUnitType"/>
 *             <element name="DataObjectReference" type="{fr:gouv:culture:archivesdefrance:seda:v2}DataObjectRefType"/>
 *             <element name="DataObjectGroup" type="{fr:gouv:culture:archivesdefrance:seda:v2}ObjectGroupRefType"/>
 *             <any processContents='lax' minOccurs="0"/>
 *           </choice>
 *         </sequence>
 *       </choice>
 *       <attribute name="id" use="required" type="{fr:gouv:culture:archivesdefrance:seda:v2}ArchiveUnitIdType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArchiveUnitType", propOrder = {
    "archiveUnitRefId",
    "archiveUnitProfile",
    "management",
    "content",
    "archiveUnitOrDataObjectReferenceOrDataObjectGroup"
})
@XmlRootElement(name = "ArchiveUnit")
public class ArchiveUnitType {

    @XmlElement(name = "ArchiveUnitRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object archiveUnitRefId;
    @XmlElement(name = "ArchiveUnitProfile")
    protected IdentifierType archiveUnitProfile;
    @XmlElement(name = "Management")
    protected ManagementType management;
    @XmlElement(name = "Content")
    protected DescriptiveMetadataContentType content;
    @XmlElementRefs({
        @XmlElementRef(name = "ArchiveUnit", namespace = "fr:gouv:culture:archivesdefrance:seda:v2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataObjectReference", namespace = "fr:gouv:culture:archivesdefrance:seda:v2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataObjectGroup", namespace = "fr:gouv:culture:archivesdefrance:seda:v2", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> archiveUnitOrDataObjectReferenceOrDataObjectGroup;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the archiveUnitRefId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getArchiveUnitRefId() {
        return archiveUnitRefId;
    }

    /**
     * Sets the value of the archiveUnitRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setArchiveUnitRefId(Object value) {
        this.archiveUnitRefId = value;
    }

    /**
     * Gets the value of the archiveUnitProfile property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getArchiveUnitProfile() {
        return archiveUnitProfile;
    }

    /**
     * Sets the value of the archiveUnitProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setArchiveUnitProfile(IdentifierType value) {
        this.archiveUnitProfile = value;
    }

    /**
     * Gets the value of the management property.
     * 
     * @return
     *     possible object is
     *     {@link ManagementType }
     *     
     */
    public ManagementType getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagementType }
     *     
     */
    public void setManagement(ManagementType value) {
        this.management = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveMetadataContentType }
     *     
     */
    public DescriptiveMetadataContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveMetadataContentType }
     *     
     */
    public void setContent(DescriptiveMetadataContentType value) {
        this.content = value;
    }

    /**
     * Gets the value of the archiveUnitOrDataObjectReferenceOrDataObjectGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the archiveUnitOrDataObjectReferenceOrDataObjectGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchiveUnitOrDataObjectReferenceOrDataObjectGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ArchiveUnitType }{@code >}
     * {@link JAXBElement }{@code <}{@link DataObjectRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link ObjectGroupRefType }{@code >}
     * {@link Object }
     * {@link Element }
     * 
     * 
     * @return
     *     The value of the archiveUnitOrDataObjectReferenceOrDataObjectGroup property.
     */
    public List<Object> getArchiveUnitOrDataObjectReferenceOrDataObjectGroup() {
        if (archiveUnitOrDataObjectReferenceOrDataObjectGroup == null) {
            archiveUnitOrDataObjectReferenceOrDataObjectGroup = new ArrayList<>();
        }
        return this.archiveUnitOrDataObjectReferenceOrDataObjectGroup;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
