//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for AuthorizationControlAuthorityRequestReplyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="AuthorizationControlAuthorityRequestReplyType">
 *   <complexContent>
 *     <extension base="{fr:gouv:culture:archivesdefrance:seda:v2}BusinessAuthorizationRequestReplyMessageType">
 *       <sequence>
 *         <element name="ArchivalAgency" type="{fr:gouv:culture:archivesdefrance:seda:v2}OrganizationWithIdType"/>
 *         <element name="ControlAuthority" type="{fr:gouv:culture:archivesdefrance:seda:v2}OrganizationWithIdType"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "AuthorizationControlAuthorityRequestReplyType",
    propOrder = {"archivalAgency", "controlAuthority"})
public class AuthorizationControlAuthorityRequestReplyType
    extends BusinessAuthorizationRequestReplyMessageType {

  /**
   * Service d'archives responsable de la réponse à une demande d'autorisation à un service de
   * contrôle.
   */
  @XmlElement(name = "ArchivalAgency", required = true)
  protected OrganizationWithIdType archivalAgency;

  /**
   * Service de contrôle responsable de la réponse à une demande d'autorisation à un service de
   * contrôle.
   */
  @XmlElement(name = "ControlAuthority", required = true)
  protected OrganizationWithIdType controlAuthority;

  /**
   * Service d'archives responsable de la réponse à une demande d'autorisation à un service de
   * contrôle.
   *
   * @return possible object is {@link OrganizationWithIdType }
   */
  public OrganizationWithIdType getArchivalAgency() {
    return archivalAgency;
  }

  /**
   * Sets the value of the archivalAgency property.
   *
   * @param value allowed object is {@link OrganizationWithIdType }
   * @see #getArchivalAgency()
   */
  public void setArchivalAgency(OrganizationWithIdType value) {
    this.archivalAgency = value;
  }

  /**
   * Service de contrôle responsable de la réponse à une demande d'autorisation à un service de
   * contrôle.
   *
   * @return possible object is {@link OrganizationWithIdType }
   */
  public OrganizationWithIdType getControlAuthority() {
    return controlAuthority;
  }

  /**
   * Sets the value of the controlAuthority property.
   *
   * @param value allowed object is {@link OrganizationWithIdType }
   * @see #getControlAuthority()
   */
  public void setControlAuthority(OrganizationWithIdType value) {
    this.controlAuthority = value;
  }
}
