//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessAuthorizationRequestMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="BusinessAuthorizationRequestMessageType">
 *   <complexContent>
 *     <extension base="{fr:gouv:culture:archivesdefrance:seda:v2}BusinessRequestMessageType">
 *       <sequence>
 *         <element name="AuthorizationRequestContent" type="{fr:gouv:culture:archivesdefrance:seda:v2}AuthorizationRequestContentType"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessAuthorizationRequestMessageType", propOrder = {
    "authorizationRequestContent"
})
@XmlSeeAlso({
    AuthorizationControlAuthorityRequestType.class,
    AuthorizationOriginatingAgencyRequestType.class
})
public abstract class BusinessAuthorizationRequestMessageType
    extends BusinessRequestMessageType
{

    @XmlElement(name = "AuthorizationRequestContent", required = true)
    protected AuthorizationRequestContentType authorizationRequestContent;

    /**
     * Gets the value of the authorizationRequestContent property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationRequestContentType }
     *     
     */
    public AuthorizationRequestContentType getAuthorizationRequestContent() {
        return authorizationRequestContent;
    }

    /**
     * Sets the value of the authorizationRequestContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationRequestContentType }
     *     
     */
    public void setAuthorizationRequestContent(AuthorizationRequestContentType value) {
        this.authorizationRequestContent = value;
    }

}
