//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BusinessMessageType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BusinessMessageType">
 *   &lt;complexContent>
 *     &lt;extension base="{fr:gouv:culture:archivesdefrance:seda:v2.1}MessageType">
 *       &lt;sequence>
 *         &lt;element name="ArchivalAgreement" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType" minOccurs="0"/>
 *         &lt;element name="CodeListVersions" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}CodeListVersionsType"/>
 *         &lt;element name="DataObjectPackage" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectPackageType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessMessageType", propOrder = {
    "archivalAgreement",
    "codeListVersions",
    "dataObjectPackage"
})
@XmlSeeAlso({
    BusinessNotificationMessageType.class,
    BusinessRequestMessageType.class,
    BusinessReplyMessageType.class
})
public abstract class BusinessMessageType
        extends MessageType {

    /**
     * The Archival agreement.
     */
    @XmlElement(name = "ArchivalAgreement")
    protected IdentifierType archivalAgreement;
    /**
     * The Code list versions.
     */
    @XmlElement(name = "CodeListVersions", required = true)
    protected CodeListVersionsType codeListVersions;
    /**
     * The Data object package.
     */
    @XmlElement(name = "DataObjectPackage")
    protected DataObjectPackageType dataObjectPackage;

    /**
     * Gets the value of the archivalAgreement property.
     *
     * @return possible object is {@link IdentifierType }
     */
    public IdentifierType getArchivalAgreement() {
        return archivalAgreement;
    }

    /**
     * Sets the value of the archivalAgreement property.
     *
     * @param value allowed object is {@link IdentifierType }
     */
    public void setArchivalAgreement(IdentifierType value) {
        this.archivalAgreement = value;
    }

    /**
     * Gets the value of the codeListVersions property.
     *
     * @return possible object is {@link CodeListVersionsType }
     */
    public CodeListVersionsType getCodeListVersions() {
        return codeListVersions;
    }

    /**
     * Sets the value of the codeListVersions property.
     *
     * @param value allowed object is {@link CodeListVersionsType }
     */
    public void setCodeListVersions(CodeListVersionsType value) {
        this.codeListVersions = value;
    }

    /**
     * Gets the value of the dataObjectPackage property.
     *
     * @return possible object is {@link DataObjectPackageType }
     */
    public DataObjectPackageType getDataObjectPackage() {
        return dataObjectPackage;
    }

    /**
     * Sets the value of the dataObjectPackage property.
     *
     * @param value allowed object is {@link DataObjectPackageType }
     */
    public void setDataObjectPackage(DataObjectPackageType value) {
        this.dataObjectPackage = value;
    }

}
