//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for BusinessReplyMessageType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BusinessReplyMessageType">
 *   &lt;complexContent>
 *     &lt;extension base="{fr:gouv:culture:archivesdefrance:seda:v2.1}BusinessMessageType">
 *       &lt;sequence>
 *         &lt;element name="ReplyCode" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/>
 *         &lt;element name="Operation" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}OperationType" minOccurs="0"/>
 *         &lt;element name="MessageRequestIdentifier" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessReplyMessageType", propOrder = {
    "replyCode",
    "operation",
    "messageRequestIdentifier"
})
@XmlSeeAlso({
    ArchiveTransferReplyType.class,
    ArchiveRestitutionRequestReplyType.class,
    ArchiveTransferRequestReplyType.class,
    ArchiveDeliveryRequestReplyType.class,
    BusinessAuthorizationRequestReplyMessageType.class
})
public abstract class BusinessReplyMessageType
        extends BusinessMessageType {

    /**
     * The Reply code.
     */
    @XmlElement(name = "ReplyCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String replyCode;
    /**
     * The Operation.
     */
    @XmlElement(name = "Operation")
    protected OperationType operation;
    /**
     * The Message request identifier.
     */
    @XmlElement(name = "MessageRequestIdentifier", required = true)
    protected IdentifierType messageRequestIdentifier;

    /**
     * Gets the value of the replyCode property.
     *
     * @return possible object is {@link String }
     */
    public String getReplyCode() {
        return replyCode;
    }

    /**
     * Sets the value of the replyCode property.
     *
     * @param value allowed object is {@link String }
     */
    public void setReplyCode(String value) {
        this.replyCode = value;
    }

    /**
     * Gets the value of the operation property.
     *
     * @return possible object is {@link OperationType }
     */
    public OperationType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     *
     * @param value allowed object is {@link OperationType }
     */
    public void setOperation(OperationType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the messageRequestIdentifier property.
     *
     * @return possible object is {@link IdentifierType }
     */
    public IdentifierType getMessageRequestIdentifier() {
        return messageRequestIdentifier;
    }

    /**
     * Sets the value of the messageRequestIdentifier property.
     *
     * @param value allowed object is {@link IdentifierType }
     */
    public void setMessageRequestIdentifier(IdentifierType value) {
        this.messageRequestIdentifier = value;
    }

}
