//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DataObjectOrArchiveUnitReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DataObjectOrArchiveUnitReferenceType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="ArchiveUnitRefId" type="{fr:gouv:culture:archivesdefrance:seda:v2}ArchiveUnitRefIdType"/>
 *         <element name="DataObjectReference" type="{fr:gouv:culture:archivesdefrance:seda:v2}DataObjectRefType"/>
 *         <element name="RepositoryArchiveUnitPID" type="{fr:gouv:culture:archivesdefrance:seda:v2}NonEmptyTokenType"/>
 *         <element name="RepositoryObjectPID" type="{fr:gouv:culture:archivesdefrance:seda:v2}NonEmptyTokenType"/>
 *         <element name="ExternalReference" type="{fr:gouv:culture:archivesdefrance:seda:v2}NonEmptyTokenType"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataObjectOrArchiveUnitReferenceType", propOrder = {
    "archiveUnitRefId",
    "dataObjectReference",
    "repositoryArchiveUnitPID",
    "repositoryObjectPID",
    "externalReference"
})
public class DataObjectOrArchiveUnitReferenceType {

    @XmlElement(name = "ArchiveUnitRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object archiveUnitRefId;
    @XmlElement(name = "DataObjectReference")
    protected DataObjectRefType dataObjectReference;
    @XmlElement(name = "RepositoryArchiveUnitPID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String repositoryArchiveUnitPID;
    @XmlElement(name = "RepositoryObjectPID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String repositoryObjectPID;
    @XmlElement(name = "ExternalReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String externalReference;

    /**
     * Gets the value of the archiveUnitRefId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getArchiveUnitRefId() {
        return archiveUnitRefId;
    }

    /**
     * Sets the value of the archiveUnitRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setArchiveUnitRefId(Object value) {
        this.archiveUnitRefId = value;
    }

    /**
     * Gets the value of the dataObjectReference property.
     * 
     * @return
     *     possible object is
     *     {@link DataObjectRefType }
     *     
     */
    public DataObjectRefType getDataObjectReference() {
        return dataObjectReference;
    }

    /**
     * Sets the value of the dataObjectReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataObjectRefType }
     *     
     */
    public void setDataObjectReference(DataObjectRefType value) {
        this.dataObjectReference = value;
    }

    /**
     * Gets the value of the repositoryArchiveUnitPID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryArchiveUnitPID() {
        return repositoryArchiveUnitPID;
    }

    /**
     * Sets the value of the repositoryArchiveUnitPID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryArchiveUnitPID(String value) {
        this.repositoryArchiveUnitPID = value;
    }

    /**
     * Gets the value of the repositoryObjectPID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryObjectPID() {
        return repositoryObjectPID;
    }

    /**
     * Sets the value of the repositoryObjectPID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryObjectPID(String value) {
        this.repositoryObjectPID = value;
    }

    /**
     * Gets the value of the externalReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReference() {
        return externalReference;
    }

    /**
     * Sets the value of the externalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReference(String value) {
        this.externalReference = value;
    }

}
