//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for ManagementType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ManagementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ManagementGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManagementType", propOrder = {
    "storageRule",
    "appraisalRule",
    "accessRule",
    "disseminationRule",
    "reuseRule",
    "classificationRule",
    "logBook",
    "needAuthorization",
    "updateOperation",
    "any"
})
public class ManagementType {

    /**
     * The Storage rule.
     */
    @XmlElement(name = "StorageRule")
    protected StorageRuleType storageRule;
    /**
     * The Appraisal rule.
     */
    @XmlElement(name = "AppraisalRule")
    protected AppraisalRuleType appraisalRule;
    /**
     * The Access rule.
     */
    @XmlElement(name = "AccessRule")
    protected AccessRuleType accessRule;
    /**
     * The Dissemination rule.
     */
    @XmlElement(name = "DisseminationRule")
    protected DisseminationRuleType disseminationRule;
    /**
     * The Reuse rule.
     */
    @XmlElement(name = "ReuseRule")
    protected ReuseRuleType reuseRule;
    /**
     * The Classification rule.
     */
    @XmlElement(name = "ClassificationRule")
    protected ClassificationRuleType classificationRule;
    /**
     * The Log book.
     */
    @XmlElement(name = "LogBook")
    protected LogBookType logBook;
    /**
     * The Need authorization.
     */
    @XmlElement(name = "NeedAuthorization")
    protected Boolean needAuthorization;
    /**
     * The Update operation.
     */
    @XmlElement(name = "UpdateOperation")
    protected UpdateOperationType updateOperation;
    /**
     * The Any.
     */
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the storageRule property.
     *
     * @return possible object is {@link StorageRuleType }
     */
    public StorageRuleType getStorageRule() {
        return storageRule;
    }

    /**
     * Sets the value of the storageRule property.
     *
     * @param value allowed object is {@link StorageRuleType }
     */
    public void setStorageRule(StorageRuleType value) {
        this.storageRule = value;
    }

    /**
     * Gets the value of the appraisalRule property.
     *
     * @return possible object is {@link AppraisalRuleType }
     */
    public AppraisalRuleType getAppraisalRule() {
        return appraisalRule;
    }

    /**
     * Sets the value of the appraisalRule property.
     *
     * @param value allowed object is {@link AppraisalRuleType }
     */
    public void setAppraisalRule(AppraisalRuleType value) {
        this.appraisalRule = value;
    }

    /**
     * Gets the value of the accessRule property.
     *
     * @return possible object is {@link AccessRuleType }
     */
    public AccessRuleType getAccessRule() {
        return accessRule;
    }

    /**
     * Sets the value of the accessRule property.
     *
     * @param value allowed object is {@link AccessRuleType }
     */
    public void setAccessRule(AccessRuleType value) {
        this.accessRule = value;
    }

    /**
     * Gets the value of the disseminationRule property.
     *
     * @return possible object is {@link DisseminationRuleType }
     */
    public DisseminationRuleType getDisseminationRule() {
        return disseminationRule;
    }

    /**
     * Sets the value of the disseminationRule property.
     *
     * @param value allowed object is {@link DisseminationRuleType }
     */
    public void setDisseminationRule(DisseminationRuleType value) {
        this.disseminationRule = value;
    }

    /**
     * Gets the value of the reuseRule property.
     *
     * @return possible object is {@link ReuseRuleType }
     */
    public ReuseRuleType getReuseRule() {
        return reuseRule;
    }

    /**
     * Sets the value of the reuseRule property.
     *
     * @param value allowed object is {@link ReuseRuleType }
     */
    public void setReuseRule(ReuseRuleType value) {
        this.reuseRule = value;
    }

    /**
     * Gets the value of the classificationRule property.
     *
     * @return possible object is {@link ClassificationRuleType }
     */
    public ClassificationRuleType getClassificationRule() {
        return classificationRule;
    }

    /**
     * Sets the value of the classificationRule property.
     *
     * @param value allowed object is {@link ClassificationRuleType }
     */
    public void setClassificationRule(ClassificationRuleType value) {
        this.classificationRule = value;
    }

    /**
     * Gets the value of the logBook property.
     *
     * @return possible object is {@link LogBookType }
     */
    public LogBookType getLogBook() {
        return logBook;
    }

    /**
     * Sets the value of the logBook property.
     *
     * @param value allowed object is {@link LogBookType }
     */
    public void setLogBook(LogBookType value) {
        this.logBook = value;
    }

    /**
     * Gets the value of the needAuthorization property.
     *
     * @return possible object is {@link Boolean }
     */
    public Boolean isNeedAuthorization() {
        return needAuthorization;
    }

    /**
     * Sets the value of the needAuthorization property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setNeedAuthorization(Boolean value) {
        this.needAuthorization = value;
    }

    /**
     * Gets the value of the updateOperation property.
     *
     * @return possible object is {@link UpdateOperationType }
     */
    public UpdateOperationType getUpdateOperation() {
        return updateOperation;
    }

    /**
     * Sets the value of the updateOperation property.
     *
     * @param value allowed object is {@link UpdateOperationType }
     */
    public void setUpdateOperation(UpdateOperationType value) {
        this.updateOperation = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null null     {@link Element }
     * {@link Object }
     *
     * @return the any
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
