//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * fr.gouv.culture.archivesdefrance.seda.v2 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OtherDimensionsAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherDimensionsAbstract");
    private final static QName _AuthorizationOriginatingAgencyRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationOriginatingAgencyRequest");
    private final static QName _ArchiveRestitutionRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveRestitutionRequestReply");
    private final static QName _ArchiveUnitReferenceAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveUnitReferenceAbstract");
    private final static QName _ArchiveTransferRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransferRequestReply");
    private final static QName _AuthorizationOriginatingAgencyRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationOriginatingAgencyRequestReply");
    private final static QName _ArchiveTransferRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransferRequest");
    private final static QName _ArchiveDeliveryRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveDeliveryRequest");
    private final static QName _ArchiveRestitutionRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveRestitutionRequest");
    private final static QName _OtherCodeListAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherCodeListAbstract");
    private final static QName _AuthorizationControlAuthorityRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationControlAuthorityRequestReply");
    private final static QName _ArchiveDestructionNotification_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveDestructionNotification");
    private final static QName _ArchiveTransfer_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransfer");
    private final static QName _OtherManagementAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherManagementAbstract");
    private final static QName _ArchiveTransferReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransferReply");
    private final static QName _ObjectGroupExtenstionAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ObjectGroupExtenstionAbstract");
    private final static QName _AgentAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AgentAbstract");
    private final static QName _OtherCoreTechnicalMetadataAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherCoreTechnicalMetadataAbstract");
    private final static QName _Acknowledgement_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Acknowledgement");
    private final static QName _AuthorizationControlAuthorityRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationControlAuthorityRequest");
    private final static QName _ArchiveModificationNotification_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveModificationNotification");
    private final static QName _EventAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "EventAbstract");
    private final static QName _ArchiveDeliveryRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveDeliveryRequestReply");
    private final static QName _ArchiveUnitTypeDataObjectGroup_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "DataObjectGroup");
    private final static QName _ArchiveUnitTypeDataObjectReference_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "DataObjectReference");
    private final static QName _ArchiveUnitTypeArchiveUnit_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveUnit");
    private final static QName _ToDeleteTypeArchiveUnitRefId_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveUnitRefId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * fr.gouv.culture.archivesdefrance.seda.v2
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthorizationOriginatingAgencyRequestType }
     *
     * @return the authorization originating agency request type
     */
    public AuthorizationOriginatingAgencyRequestType createAuthorizationOriginatingAgencyRequestType() {
        return new AuthorizationOriginatingAgencyRequestType();
    }

    /**
     * Create an instance of {@link AuthorizationControlAuthorityRequestReplyType
     * }*
     *
     * @return the authorization control authority request reply type
     */
    public AuthorizationControlAuthorityRequestReplyType createAuthorizationControlAuthorityRequestReplyType() {
        return new AuthorizationControlAuthorityRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveDestructionNotificationType }
     *
     * @return the archive destruction notification type
     */
    public ArchiveDestructionNotificationType createArchiveDestructionNotificationType() {
        return new ArchiveDestructionNotificationType();
    }

    /**
     * Create an instance of {@link ArchiveTransferType }
     *
     * @return the archive transfer type
     */
    public ArchiveTransferType createArchiveTransferType() {
        return new ArchiveTransferType();
    }

    /**
     * Create an instance of {@link AgentType }
     *
     * @return the agent type
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link ArchiveTransferReplyType }
     *
     * @return the archive transfer reply type
     */
    public ArchiveTransferReplyType createArchiveTransferReplyType() {
        return new ArchiveTransferReplyType();
    }

    /**
     * Create an instance of {@link ArchiveRestitutionRequestReplyType }
     *
     * @return the archive restitution request reply type
     */
    public ArchiveRestitutionRequestReplyType createArchiveRestitutionRequestReplyType() {
        return new ArchiveRestitutionRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveTransferRequestReplyType }
     *
     * @return the archive transfer request reply type
     */
    public ArchiveTransferRequestReplyType createArchiveTransferRequestReplyType() {
        return new ArchiveTransferRequestReplyType();
    }

    /**
     * Create an instance of {@link AuthorizationOriginatingAgencyRequestReplyType
     * }*
     *
     * @return the authorization originating agency request reply type
     */
    public AuthorizationOriginatingAgencyRequestReplyType createAuthorizationOriginatingAgencyRequestReplyType() {
        return new AuthorizationOriginatingAgencyRequestReplyType();
    }

    /**
     * Create an instance of {@link AuthorizationControlAuthorityRequestType }
     *
     * @return the authorization control authority request type
     */
    public AuthorizationControlAuthorityRequestType createAuthorizationControlAuthorityRequestType() {
        return new AuthorizationControlAuthorityRequestType();
    }

    /**
     * Create an instance of {@link AcknowledgementType }
     *
     * @return the acknowledgement type
     */
    public AcknowledgementType createAcknowledgementType() {
        return new AcknowledgementType();
    }

    /**
     * Create an instance of {@link ArchiveDeliveryRequestType }
     *
     * @return the archive delivery request type
     */
    public ArchiveDeliveryRequestType createArchiveDeliveryRequestType() {
        return new ArchiveDeliveryRequestType();
    }

    /**
     * Create an instance of {@link ArchiveRestitutionRequestType }
     *
     * @return the archive restitution request type
     */
    public ArchiveRestitutionRequestType createArchiveRestitutionRequestType() {
        return new ArchiveRestitutionRequestType();
    }

    /**
     * Create an instance of {@link ArchiveTransferRequestType }
     *
     * @return the archive transfer request type
     */
    public ArchiveTransferRequestType createArchiveTransferRequestType() {
        return new ArchiveTransferRequestType();
    }

    /**
     * Create an instance of {@link ArchiveDeliveryRequestReplyType }
     *
     * @return the archive delivery request reply type
     */
    public ArchiveDeliveryRequestReplyType createArchiveDeliveryRequestReplyType() {
        return new ArchiveDeliveryRequestReplyType();
    }

    /**
     * Create an instance of {@link CodeType }
     *
     * @return the code type
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link ArchiveModificationNotificationType }
     *
     * @return the archive modification notification type
     */
    public ArchiveModificationNotificationType createArchiveModificationNotificationType() {
        return new ArchiveModificationNotificationType();
    }

    /**
     * Create an instance of {@link CustodialHistoryItemType }
     *
     * @return the custodial history item type
     */
    public CustodialHistoryItemType createCustodialHistoryItemType() {
        return new CustodialHistoryItemType();
    }

    /**
     * Create an instance of {@link ImageTechnicalMetadataType }
     *
     * @return the image technical metadata type
     */
    public ImageTechnicalMetadataType createImageTechnicalMetadataType() {
        return new ImageTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataType }
     *
     * @return the descriptive metadata type
     */
    public DescriptiveMetadataType createDescriptiveMetadataType() {
        return new DescriptiveMetadataType();
    }

    /**
     * Create an instance of {@link ReferencedObjectType }
     *
     * @return the referenced object type
     */
    public ReferencedObjectType createReferencedObjectType() {
        return new ReferencedObjectType();
    }

    /**
     * Create an instance of {@link FileInfoType }
     *
     * @return the file info type
     */
    public FileInfoType createFileInfoType() {
        return new FileInfoType();
    }

    /**
     * Create an instance of {@link FormatIdentificationType }
     *
     * @return the format identification type
     */
    public FormatIdentificationType createFormatIdentificationType() {
        return new FormatIdentificationType();
    }

    /**
     * Create an instance of {@link CoverageType }
     *
     * @return the coverage type
     */
    public CoverageType createCoverageType() {
        return new CoverageType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType }
     *
     * @return the descriptive metadata content type
     */
    public DescriptiveMetadataContentType createDescriptiveMetadataContentType() {
        return new DescriptiveMetadataContentType();
    }

    /**
     * Create an instance of {@link CustodialHistoryType }
     *
     * @return the custodial history type
     */
    public CustodialHistoryType createCustodialHistoryType() {
        return new CustodialHistoryType();
    }

    /**
     * Create an instance of {@link CodeListVersionsType }
     *
     * @return the code list versions type
     */
    public CodeListVersionsType createCodeListVersionsType() {
        return new CodeListVersionsType();
    }

    /**
     * Create an instance of {@link ReuseRuleType }
     *
     * @return the reuse rule type
     */
    public ReuseRuleType createReuseRuleType() {
        return new ReuseRuleType();
    }

    /**
     * Create an instance of {@link ObjectGroupRefType }
     *
     * @return the object group ref type
     */
    public ObjectGroupRefType createObjectGroupRefType() {
        return new ObjectGroupRefType();
    }

    /**
     * Create an instance of {@link TextType }
     *
     * @return the text type
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link AudioTechnicalMetadataType }
     *
     * @return the audio technical metadata type
     */
    public AudioTechnicalMetadataType createAudioTechnicalMetadataType() {
        return new AudioTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link CoreMetadataType }
     *
     * @return the core metadata type
     */
    public CoreMetadataType createCoreMetadataType() {
        return new CoreMetadataType();
    }

    /**
     * Create an instance of {@link DataObjectGroupType }
     *
     * @return the data object group type
     */
    public DataObjectGroupType createDataObjectGroupType() {
        return new DataObjectGroupType();
    }

    /**
     * Create an instance of {@link KeywordsType }
     *
     * @return the keywords type
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link BinaryObjectType }
     *
     * @return the binary object type
     */
    public BinaryObjectType createBinaryObjectType() {
        return new BinaryObjectType();
    }

    /**
     * Create an instance of {@link AppraisalRuleType }
     *
     * @return the appraisal rule type
     */
    public AppraisalRuleType createAppraisalRuleType() {
        return new AppraisalRuleType();
    }

    /**
     * Create an instance of {@link OperationType }
     *
     * @return the operation type
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link TextTechnicalMetadataType }
     *
     * @return the text technical metadata type
     */
    public TextTechnicalMetadataType createTextTechnicalMetadataType() {
        return new TextTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link PhysicalDataObjectType }
     *
     * @return the physical data object type
     */
    public PhysicalDataObjectType createPhysicalDataObjectType() {
        return new PhysicalDataObjectType();
    }

    /**
     * Create an instance of {@link DataObjectOrArchiveUnitReferenceType }
     *
     * @return the data object or archive unit reference type
     */
    public DataObjectOrArchiveUnitReferenceType createDataObjectOrArchiveUnitReferenceType() {
        return new DataObjectOrArchiveUnitReferenceType();
    }

    /**
     * Create an instance of {@link ManagementHistoryType }
     *
     * @return the management history type
     */
    public ManagementHistoryType createManagementHistoryType() {
        return new ManagementHistoryType();
    }

    /**
     * Create an instance of {@link OrganizationDescriptiveMetadataType }
     *
     * @return the organization descriptive metadata type
     */
    public OrganizationDescriptiveMetadataType createOrganizationDescriptiveMetadataType() {
        return new OrganizationDescriptiveMetadataType();
    }

    /**
     * Create an instance of {@link BirthOrDeathPlaceType }
     *
     * @return the birth or death place type
     */
    public BirthOrDeathPlaceType createBirthOrDeathPlaceType() {
        return new BirthOrDeathPlaceType();
    }

    /**
     * Create an instance of {@link OrganizationWithIdType }
     *
     * @return the organization with id type
     */
    public OrganizationWithIdType createOrganizationWithIdType() {
        return new OrganizationWithIdType();
    }

    /**
     * Create an instance of {@link EventLogBookOgType }
     *
     * @return the event log book og type
     */
    public EventLogBookOgType createEventLogBookOgType() {
        return new EventLogBookOgType();
    }

    /**
     * Create an instance of {@link ClassificationRuleType }
     *
     * @return the classification rule type
     */
    public ClassificationRuleType createClassificationRuleType() {
        return new ClassificationRuleType();
    }

    /**
     * Create an instance of {@link KeyType }
     *
     * @return the key type
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link EventType }
     *
     * @return the event type
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     *
     * @return the relationship type
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link SignerType }
     *
     * @return the signer type
     */
    public SignerType createSignerType() {
        return new SignerType();
    }

    /**
     * Create an instance of {@link GpsType }
     *
     * @return the gps type
     */
    public GpsType createGpsType() {
        return new GpsType();
    }

    /**
     * Create an instance of {@link BinaryDataObjectType }
     *
     * @return the binary data object type
     */
    public BinaryDataObjectType createBinaryDataObjectType() {
        return new BinaryDataObjectType();
    }

    /**
     * Create an instance of {@link DisseminationRuleType }
     *
     * @return the dissemination rule type
     */
    public DisseminationRuleType createDisseminationRuleType() {
        return new DisseminationRuleType();
    }

    /**
     * Create an instance of {@link LogBookType }
     *
     * @return the log book type
     */
    public LogBookType createLogBookType() {
        return new LogBookType();
    }

    /**
     * Create an instance of {@link MeasurementWeightType }
     *
     * @return the measurement weight type
     */
    public MeasurementWeightType createMeasurementWeightType() {
        return new MeasurementWeightType();
    }

    /**
     * Create an instance of {@link SignatureType }
     *
     * @return the signature type
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link ValidatorType }
     *
     * @return the validator type
     */
    public ValidatorType createValidatorType() {
        return new ValidatorType();
    }

    /**
     * Create an instance of {@link CompressedType }
     *
     * @return the compressed type
     */
    public CompressedType createCompressedType() {
        return new CompressedType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     *
     * @return the identifier type
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link LogBookOgType }
     *
     * @return the log book og type
     */
    public LogBookOgType createLogBookOgType() {
        return new LogBookOgType();
    }

    /**
     * Create an instance of {@link ArchiveUnitIdentifierKeyType }
     *
     * @return the archive unit identifier key type
     */
    public ArchiveUnitIdentifierKeyType createArchiveUnitIdentifierKeyType() {
        return new ArchiveUnitIdentifierKeyType();
    }

    /**
     * Create an instance of {@link ManagementHistoryDataType }
     *
     * @return the management history data type
     */
    public ManagementHistoryDataType createManagementHistoryDataType() {
        return new ManagementHistoryDataType();
    }

    /**
     * Create an instance of {@link ArchiveUnitType }
     *
     * @return the archive unit type
     */
    public ArchiveUnitType createArchiveUnitType() {
        return new ArchiveUnitType();
    }

    /**
     * Create an instance of {@link VideoTechnicalMetadataType }
     *
     * @return the video technical metadata type
     */
    public VideoTechnicalMetadataType createVideoTechnicalMetadataType() {
        return new VideoTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link DocumentTechnicalMetadataType }
     *
     * @return the document technical metadata type
     */
    public DocumentTechnicalMetadataType createDocumentTechnicalMetadataType() {
        return new DocumentTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link SignatureMessageType }
     *
     * @return the signature message type
     */
    public SignatureMessageType createSignatureMessageType() {
        return new SignatureMessageType();
    }

    /**
     * Create an instance of {@link StorageRuleType }
     *
     * @return the storage rule type
     */
    public StorageRuleType createStorageRuleType() {
        return new StorageRuleType();
    }

    /**
     * Create an instance of {@link UpdateOperationType }
     *
     * @return the update operation type
     */
    public UpdateOperationType createUpdateOperationType() {
        return new UpdateOperationType();
    }

    /**
     * Create an instance of {@link DataObjectRefType }
     *
     * @return the data object ref type
     */
    public DataObjectRefType createDataObjectRefType() {
        return new DataObjectRefType();
    }

    /**
     * Create an instance of {@link MeasurementType }
     *
     * @return the measurement type
     */
    public MeasurementType createMeasurementType() {
        return new MeasurementType();
    }

    /**
     * Create an instance of {@link ManagementMetadataType }
     *
     * @return the management metadata type
     */
    public ManagementMetadataType createManagementMetadataType() {
        return new ManagementMetadataType();
    }

    /**
     * Create an instance of {@link RelatedObjectReferenceType }
     *
     * @return the related object reference type
     */
    public RelatedObjectReferenceType createRelatedObjectReferenceType() {
        return new RelatedObjectReferenceType();
    }

    /**
     * Create an instance of {@link AuthorizationRequestContentType }
     *
     * @return the authorization request content type
     */
    public AuthorizationRequestContentType createAuthorizationRequestContentType() {
        return new AuthorizationRequestContentType();
    }

    /**
     * Create an instance of {@link ManagementType }
     *
     * @return the management type
     */
    public ManagementType createManagementType() {
        return new ManagementType();
    }

    /**
     * Create an instance of {@link DescriptiveTechnicalMetadataType }
     *
     * @return the descriptive technical metadata type
     */
    public DescriptiveTechnicalMetadataType createDescriptiveTechnicalMetadataType() {
        return new DescriptiveTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     *
     * @return the organization type
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link RuleIdType }
     *
     * @return the rule id type
     */
    public RuleIdType createRuleIdType() {
        return new RuleIdType();
    }

    /**
     * Create an instance of {@link MessageDigestBinaryObjectType }
     *
     * @return the message digest binary object type
     */
    public MessageDigestBinaryObjectType createMessageDigestBinaryObjectType() {
        return new MessageDigestBinaryObjectType();
    }

    /**
     * Create an instance of {@link ToDeleteType }
     *
     * @return the to delete type
     */
    public ToDeleteType createToDeleteType() {
        return new ToDeleteType();
    }

    /**
     * Create an instance of {@link DimensionsType }
     *
     * @return the dimensions type
     */
    public DimensionsType createDimensionsType() {
        return new DimensionsType();
    }

    /**
     * Create an instance of {@link AccessRuleType }
     *
     * @return the access rule type
     */
    public AccessRuleType createAccessRuleType() {
        return new AccessRuleType();
    }

    /**
     * Create an instance of {@link DataObjectPackageType }
     *
     * @return the data object package type
     */
    public DataObjectPackageType createDataObjectPackageType() {
        return new DataObjectPackageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherDimensionsAbstract")
    public JAXBElement<Object> createOtherDimensionsAbstract(Object value) {
        return new JAXBElement<Object>(_OtherDimensionsAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationOriginatingAgencyRequest")
    public JAXBElement<AuthorizationOriginatingAgencyRequestType> createAuthorizationOriginatingAgencyRequest(AuthorizationOriginatingAgencyRequestType value) {
        return new JAXBElement<AuthorizationOriginatingAgencyRequestType>(_AuthorizationOriginatingAgencyRequest_QNAME, AuthorizationOriginatingAgencyRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestReplyType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveRestitutionRequestReply")
    public JAXBElement<ArchiveRestitutionRequestReplyType> createArchiveRestitutionRequestReply(ArchiveRestitutionRequestReplyType value) {
        return new JAXBElement<ArchiveRestitutionRequestReplyType>(_ArchiveRestitutionRequestReply_QNAME, ArchiveRestitutionRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveUnitReferenceAbstract")
    public JAXBElement<Object> createArchiveUnitReferenceAbstract(Object value) {
        return new JAXBElement<Object>(_ArchiveUnitReferenceAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestReplyType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransferRequestReply")
    public JAXBElement<ArchiveTransferRequestReplyType> createArchiveTransferRequestReply(ArchiveTransferRequestReplyType value) {
        return new JAXBElement<ArchiveTransferRequestReplyType>(_ArchiveTransferRequestReply_QNAME, ArchiveTransferRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestReplyType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationOriginatingAgencyRequestReply")
    public JAXBElement<AuthorizationOriginatingAgencyRequestReplyType> createAuthorizationOriginatingAgencyRequestReply(AuthorizationOriginatingAgencyRequestReplyType value) {
        return new JAXBElement<AuthorizationOriginatingAgencyRequestReplyType>(_AuthorizationOriginatingAgencyRequestReply_QNAME, AuthorizationOriginatingAgencyRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransferRequest")
    public JAXBElement<ArchiveTransferRequestType> createArchiveTransferRequest(ArchiveTransferRequestType value) {
        return new JAXBElement<ArchiveTransferRequestType>(_ArchiveTransferRequest_QNAME, ArchiveTransferRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveDeliveryRequest")
    public JAXBElement<ArchiveDeliveryRequestType> createArchiveDeliveryRequest(ArchiveDeliveryRequestType value) {
        return new JAXBElement<ArchiveDeliveryRequestType>(_ArchiveDeliveryRequest_QNAME, ArchiveDeliveryRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveRestitutionRequest")
    public JAXBElement<ArchiveRestitutionRequestType> createArchiveRestitutionRequest(ArchiveRestitutionRequestType value) {
        return new JAXBElement<ArchiveRestitutionRequestType>(_ArchiveRestitutionRequest_QNAME, ArchiveRestitutionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherCodeListAbstract")
    public JAXBElement<CodeType> createOtherCodeListAbstract(CodeType value) {
        return new JAXBElement<CodeType>(_OtherCodeListAbstract_QNAME, CodeType.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestReplyType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationControlAuthorityRequestReply")
    public JAXBElement<AuthorizationControlAuthorityRequestReplyType> createAuthorizationControlAuthorityRequestReply(AuthorizationControlAuthorityRequestReplyType value) {
        return new JAXBElement<AuthorizationControlAuthorityRequestReplyType>(_AuthorizationControlAuthorityRequestReply_QNAME, AuthorizationControlAuthorityRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDestructionNotificationType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveDestructionNotification")
    public JAXBElement<ArchiveDestructionNotificationType> createArchiveDestructionNotification(ArchiveDestructionNotificationType value) {
        return new JAXBElement<ArchiveDestructionNotificationType>(_ArchiveDestructionNotification_QNAME, ArchiveDestructionNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransfer")
    public JAXBElement<ArchiveTransferType> createArchiveTransfer(ArchiveTransferType value) {
        return new JAXBElement<ArchiveTransferType>(_ArchiveTransfer_QNAME, ArchiveTransferType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherManagementAbstract")
    public JAXBElement<Object> createOtherManagementAbstract(Object value) {
        return new JAXBElement<Object>(_OtherManagementAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferReplyType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransferReply")
    public JAXBElement<ArchiveTransferReplyType> createArchiveTransferReply(ArchiveTransferReplyType value) {
        return new JAXBElement<ArchiveTransferReplyType>(_ArchiveTransferReply_QNAME, ArchiveTransferReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ObjectGroupExtenstionAbstract")
    public JAXBElement<Object> createObjectGroupExtenstionAbstract(Object value) {
        return new JAXBElement<Object>(_ObjectGroupExtenstionAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AgentAbstract")
    public JAXBElement<AgentType> createAgentAbstract(AgentType value) {
        return new JAXBElement<AgentType>(_AgentAbstract_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherCoreTechnicalMetadataAbstract")
    public JAXBElement<OpenType> createOtherCoreTechnicalMetadataAbstract(OpenType value) {
        return new JAXBElement<OpenType>(_OtherCoreTechnicalMetadataAbstract_QNAME, OpenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgementType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Acknowledgement")
    public JAXBElement<AcknowledgementType> createAcknowledgement(AcknowledgementType value) {
        return new JAXBElement<AcknowledgementType>(_Acknowledgement_QNAME, AcknowledgementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationControlAuthorityRequest")
    public JAXBElement<AuthorizationControlAuthorityRequestType> createAuthorizationControlAuthorityRequest(AuthorizationControlAuthorityRequestType value) {
        return new JAXBElement<AuthorizationControlAuthorityRequestType>(_AuthorizationControlAuthorityRequest_QNAME, AuthorizationControlAuthorityRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveModificationNotificationType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveModificationNotification")
    public JAXBElement<ArchiveModificationNotificationType> createArchiveModificationNotification(ArchiveModificationNotificationType value) {
        return new JAXBElement<ArchiveModificationNotificationType>(_ArchiveModificationNotification_QNAME, ArchiveModificationNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "EventAbstract")
    public JAXBElement<Object> createEventAbstract(Object value) {
        return new JAXBElement<Object>(_EventAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestReplyType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveDeliveryRequestReply")
    public JAXBElement<ArchiveDeliveryRequestReplyType> createArchiveDeliveryRequestReply(ArchiveDeliveryRequestReplyType value) {
        return new JAXBElement<ArchiveDeliveryRequestReplyType>(_ArchiveDeliveryRequestReply_QNAME, ArchiveDeliveryRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectGroupRefType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DataObjectGroup", scope = ArchiveUnitType.class)
    public JAXBElement<ObjectGroupRefType> createArchiveUnitTypeDataObjectGroup(ObjectGroupRefType value) {
        return new JAXBElement<ObjectGroupRefType>(_ArchiveUnitTypeDataObjectGroup_QNAME, ObjectGroupRefType.class, ArchiveUnitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectRefType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DataObjectReference", scope = ArchiveUnitType.class)
    public JAXBElement<DataObjectRefType> createArchiveUnitTypeDataObjectReference(DataObjectRefType value) {
        return new JAXBElement<DataObjectRefType>(_ArchiveUnitTypeDataObjectReference_QNAME, DataObjectRefType.class, ArchiveUnitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveUnitType }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveUnit", scope = ArchiveUnitType.class)
    public JAXBElement<ArchiveUnitType> createArchiveUnitTypeArchiveUnit(ArchiveUnitType value) {
        return new JAXBElement<ArchiveUnitType>(_ArchiveUnitTypeArchiveUnit_QNAME, ArchiveUnitType.class, ArchiveUnitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     * @param value the value
     * @return the jaxb element
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveUnitRefId", scope = ToDeleteType.class)
    @XmlIDREF
    public JAXBElement<Object> createToDeleteTypeArchiveUnitRefId(Object value) {
        return new JAXBElement<Object>(_ToDeleteTypeArchiveUnitRefId_QNAME, Object.class, ToDeleteType.class, value);
    }

}
