//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.gouv.culture.archivesdefrance.seda.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ObjectGroupExtenstionAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ObjectGroupExtenstionAbstract");
    private static final QName _OtherDimensionsAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "OtherDimensionsAbstract");
    private static final QName _OtherCoreTechnicalMetadataAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "OtherCoreTechnicalMetadataAbstract");
    private static final QName _ArchiveUnitReferenceAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveUnitReferenceAbstract");
    private static final QName _OtherManagementAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "OtherManagementAbstract");
    private static final QName _OtherCodeListAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "OtherCodeListAbstract");
    private static final QName _EventAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "EventAbstract");
    private static final QName _Acknowledgement_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "Acknowledgement");
    private static final QName _ArchiveDeliveryRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveDeliveryRequest");
    private static final QName _ArchiveRestitutionRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveRestitutionRequest");
    private static final QName _ArchiveTransfer_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveTransfer");
    private static final QName _ArchiveTransferRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveTransferRequest");
    private static final QName _AuthorizationControlAuthorityRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "AuthorizationControlAuthorityRequest");
    private static final QName _AuthorizationOriginatingAgencyRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "AuthorizationOriginatingAgencyRequest");
    private static final QName _ArchiveDeliveryRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveDeliveryRequestReply");
    private static final QName _ArchiveRestitutionRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveRestitutionRequestReply");
    private static final QName _ArchiveTransferReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveTransferReply");
    private static final QName _ArchiveTransferRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveTransferRequestReply");
    private static final QName _AuthorizationControlAuthorityRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "AuthorizationControlAuthorityRequestReply");
    private static final QName _AuthorizationOriginatingAgencyRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "AuthorizationOriginatingAgencyRequestReply");
    private static final QName _ArchiveDestructionNotification_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveDestructionNotification");
    private static final QName _ArchiveModificationNotification_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveModificationNotification");
    private static final QName _ArchiveUnitTypeArchiveUnit_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveUnit");
    private static final QName _ArchiveUnitTypeDataObjectReference_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "DataObjectReference");
    private static final QName _ArchiveUnitTypeDataObjectGroup_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "DataObjectGroup");
    private static final QName _ToDeleteTypeArchiveUnitRefId_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "ArchiveUnitRefId");
    private static final QName _HoldRuleTypeRule_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "Rule");
    private static final QName _HoldRuleTypeStartDate_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "StartDate");
    private static final QName _HoldRuleTypeHoldEndDate_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "HoldEndDate");
    private static final QName _HoldRuleTypeHoldOwner_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "HoldOwner");
    private static final QName _HoldRuleTypeHoldReassessingDate_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "HoldReassessingDate");
    private static final QName _HoldRuleTypeHoldReason_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "HoldReason");
    private static final QName _HoldRuleTypePreventRearrangement_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2", "PreventRearrangement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.gouv.culture.archivesdefrance.seda.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     * @return
     *     the new instance of {@link CodeType }
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link AcknowledgementType }
     * 
     * @return
     *     the new instance of {@link AcknowledgementType }
     */
    public AcknowledgementType createAcknowledgementType() {
        return new AcknowledgementType();
    }

    /**
     * Create an instance of {@link ArchiveDeliveryRequestType }
     * 
     * @return
     *     the new instance of {@link ArchiveDeliveryRequestType }
     */
    public ArchiveDeliveryRequestType createArchiveDeliveryRequestType() {
        return new ArchiveDeliveryRequestType();
    }

    /**
     * Create an instance of {@link ArchiveRestitutionRequestType }
     * 
     * @return
     *     the new instance of {@link ArchiveRestitutionRequestType }
     */
    public ArchiveRestitutionRequestType createArchiveRestitutionRequestType() {
        return new ArchiveRestitutionRequestType();
    }

    /**
     * Create an instance of {@link ArchiveTransferType }
     * 
     * @return
     *     the new instance of {@link ArchiveTransferType }
     */
    public ArchiveTransferType createArchiveTransferType() {
        return new ArchiveTransferType();
    }

    /**
     * Create an instance of {@link ArchiveTransferRequestType }
     * 
     * @return
     *     the new instance of {@link ArchiveTransferRequestType }
     */
    public ArchiveTransferRequestType createArchiveTransferRequestType() {
        return new ArchiveTransferRequestType();
    }

    /**
     * Create an instance of {@link AuthorizationControlAuthorityRequestType }
     * 
     * @return
     *     the new instance of {@link AuthorizationControlAuthorityRequestType }
     */
    public AuthorizationControlAuthorityRequestType createAuthorizationControlAuthorityRequestType() {
        return new AuthorizationControlAuthorityRequestType();
    }

    /**
     * Create an instance of {@link AuthorizationOriginatingAgencyRequestType }
     * 
     * @return
     *     the new instance of {@link AuthorizationOriginatingAgencyRequestType }
     */
    public AuthorizationOriginatingAgencyRequestType createAuthorizationOriginatingAgencyRequestType() {
        return new AuthorizationOriginatingAgencyRequestType();
    }

    /**
     * Create an instance of {@link ArchiveDeliveryRequestReplyType }
     * 
     * @return
     *     the new instance of {@link ArchiveDeliveryRequestReplyType }
     */
    public ArchiveDeliveryRequestReplyType createArchiveDeliveryRequestReplyType() {
        return new ArchiveDeliveryRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveRestitutionRequestReplyType }
     * 
     * @return
     *     the new instance of {@link ArchiveRestitutionRequestReplyType }
     */
    public ArchiveRestitutionRequestReplyType createArchiveRestitutionRequestReplyType() {
        return new ArchiveRestitutionRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveTransferReplyType }
     * 
     * @return
     *     the new instance of {@link ArchiveTransferReplyType }
     */
    public ArchiveTransferReplyType createArchiveTransferReplyType() {
        return new ArchiveTransferReplyType();
    }

    /**
     * Create an instance of {@link ArchiveTransferRequestReplyType }
     * 
     * @return
     *     the new instance of {@link ArchiveTransferRequestReplyType }
     */
    public ArchiveTransferRequestReplyType createArchiveTransferRequestReplyType() {
        return new ArchiveTransferRequestReplyType();
    }

    /**
     * Create an instance of {@link AuthorizationControlAuthorityRequestReplyType }
     * 
     * @return
     *     the new instance of {@link AuthorizationControlAuthorityRequestReplyType }
     */
    public AuthorizationControlAuthorityRequestReplyType createAuthorizationControlAuthorityRequestReplyType() {
        return new AuthorizationControlAuthorityRequestReplyType();
    }

    /**
     * Create an instance of {@link AuthorizationOriginatingAgencyRequestReplyType }
     * 
     * @return
     *     the new instance of {@link AuthorizationOriginatingAgencyRequestReplyType }
     */
    public AuthorizationOriginatingAgencyRequestReplyType createAuthorizationOriginatingAgencyRequestReplyType() {
        return new AuthorizationOriginatingAgencyRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveDestructionNotificationType }
     * 
     * @return
     *     the new instance of {@link ArchiveDestructionNotificationType }
     */
    public ArchiveDestructionNotificationType createArchiveDestructionNotificationType() {
        return new ArchiveDestructionNotificationType();
    }

    /**
     * Create an instance of {@link ArchiveModificationNotificationType }
     * 
     * @return
     *     the new instance of {@link ArchiveModificationNotificationType }
     */
    public ArchiveModificationNotificationType createArchiveModificationNotificationType() {
        return new ArchiveModificationNotificationType();
    }

    /**
     * Create an instance of {@link CustodialHistoryType }
     * 
     * @return
     *     the new instance of {@link CustodialHistoryType }
     */
    public CustodialHistoryType createCustodialHistoryType() {
        return new CustodialHistoryType();
    }

    /**
     * Create an instance of {@link CustodialHistoryItemType }
     * 
     * @return
     *     the new instance of {@link CustodialHistoryItemType }
     */
    public CustodialHistoryItemType createCustodialHistoryItemType() {
        return new CustodialHistoryItemType();
    }

    /**
     * Create an instance of {@link KeywordsType }
     * 
     * @return
     *     the new instance of {@link KeywordsType }
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     * @return
     *     the new instance of {@link KeyType }
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link CoverageType }
     * 
     * @return
     *     the new instance of {@link CoverageType }
     */
    public CoverageType createCoverageType() {
        return new CoverageType();
    }

    /**
     * Create an instance of {@link RelatedObjectReferenceType }
     * 
     * @return
     *     the new instance of {@link RelatedObjectReferenceType }
     */
    public RelatedObjectReferenceType createRelatedObjectReferenceType() {
        return new RelatedObjectReferenceType();
    }

    /**
     * Create an instance of {@link DataObjectOrArchiveUnitReferenceType }
     * 
     * @return
     *     the new instance of {@link DataObjectOrArchiveUnitReferenceType }
     */
    public DataObjectOrArchiveUnitReferenceType createDataObjectOrArchiveUnitReferenceType() {
        return new DataObjectOrArchiveUnitReferenceType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     * @return
     *     the new instance of {@link EventType }
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link LinkingAgentIdentifierType }
     * 
     * @return
     *     the new instance of {@link LinkingAgentIdentifierType }
     */
    public LinkingAgentIdentifierType createLinkingAgentIdentifierType() {
        return new LinkingAgentIdentifierType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     * @return
     *     the new instance of {@link SignatureType }
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link SignerType }
     * 
     * @return
     *     the new instance of {@link SignerType }
     */
    public SignerType createSignerType() {
        return new SignerType();
    }

    /**
     * Create an instance of {@link ValidatorType }
     * 
     * @return
     *     the new instance of {@link ValidatorType }
     */
    public ValidatorType createValidatorType() {
        return new ValidatorType();
    }

    /**
     * Create an instance of {@link ReferencedObjectType }
     * 
     * @return
     *     the new instance of {@link ReferencedObjectType }
     */
    public ReferencedObjectType createReferencedObjectType() {
        return new ReferencedObjectType();
    }

    /**
     * Create an instance of {@link AgentType }
     * 
     * @return
     *     the new instance of {@link AgentType }
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link BirthOrDeathPlaceType }
     * 
     * @return
     *     the new instance of {@link BirthOrDeathPlaceType }
     */
    public BirthOrDeathPlaceType createBirthOrDeathPlaceType() {
        return new BirthOrDeathPlaceType();
    }

    /**
     * Create an instance of {@link GpsType }
     * 
     * @return
     *     the new instance of {@link GpsType }
     */
    public GpsType createGpsType() {
        return new GpsType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     * @return
     *     the new instance of {@link TextType }
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     * @return
     *     the new instance of {@link IdentifierType }
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link DataObjectRefType }
     * 
     * @return
     *     the new instance of {@link DataObjectRefType }
     */
    public DataObjectRefType createDataObjectRefType() {
        return new DataObjectRefType();
    }

    /**
     * Create an instance of {@link MessageDigestBinaryObjectType }
     * 
     * @return
     *     the new instance of {@link MessageDigestBinaryObjectType }
     */
    public MessageDigestBinaryObjectType createMessageDigestBinaryObjectType() {
        return new MessageDigestBinaryObjectType();
    }

    /**
     * Create an instance of {@link BinaryObjectType }
     * 
     * @return
     *     the new instance of {@link BinaryObjectType }
     */
    public BinaryObjectType createBinaryObjectType() {
        return new BinaryObjectType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     * @return
     *     the new instance of {@link RelationshipType }
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     * @return
     *     the new instance of {@link OrganizationType }
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link OrganizationDescriptiveMetadataType }
     * 
     * @return
     *     the new instance of {@link OrganizationDescriptiveMetadataType }
     */
    public OrganizationDescriptiveMetadataType createOrganizationDescriptiveMetadataType() {
        return new OrganizationDescriptiveMetadataType();
    }

    /**
     * Create an instance of {@link SignatureMessageType }
     * 
     * @return
     *     the new instance of {@link SignatureMessageType }
     */
    public SignatureMessageType createSignatureMessageType() {
        return new SignatureMessageType();
    }

    /**
     * Create an instance of {@link TextTechnicalMetadataType }
     * 
     * @return
     *     the new instance of {@link TextTechnicalMetadataType }
     */
    public TextTechnicalMetadataType createTextTechnicalMetadataType() {
        return new TextTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link DocumentTechnicalMetadataType }
     * 
     * @return
     *     the new instance of {@link DocumentTechnicalMetadataType }
     */
    public DocumentTechnicalMetadataType createDocumentTechnicalMetadataType() {
        return new DocumentTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link ImageTechnicalMetadataType }
     * 
     * @return
     *     the new instance of {@link ImageTechnicalMetadataType }
     */
    public ImageTechnicalMetadataType createImageTechnicalMetadataType() {
        return new ImageTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link AudioTechnicalMetadataType }
     * 
     * @return
     *     the new instance of {@link AudioTechnicalMetadataType }
     */
    public AudioTechnicalMetadataType createAudioTechnicalMetadataType() {
        return new AudioTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link VideoTechnicalMetadataType }
     * 
     * @return
     *     the new instance of {@link VideoTechnicalMetadataType }
     */
    public VideoTechnicalMetadataType createVideoTechnicalMetadataType() {
        return new VideoTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link DescriptiveTechnicalMetadataType }
     * 
     * @return
     *     the new instance of {@link DescriptiveTechnicalMetadataType }
     */
    public DescriptiveTechnicalMetadataType createDescriptiveTechnicalMetadataType() {
        return new DescriptiveTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link BinaryDataObjectType }
     * 
     * @return
     *     the new instance of {@link BinaryDataObjectType }
     */
    public BinaryDataObjectType createBinaryDataObjectType() {
        return new BinaryDataObjectType();
    }

    /**
     * Create an instance of {@link CompressedType }
     * 
     * @return
     *     the new instance of {@link CompressedType }
     */
    public CompressedType createCompressedType() {
        return new CompressedType();
    }

    /**
     * Create an instance of {@link FormatIdentificationType }
     * 
     * @return
     *     the new instance of {@link FormatIdentificationType }
     */
    public FormatIdentificationType createFormatIdentificationType() {
        return new FormatIdentificationType();
    }

    /**
     * Create an instance of {@link FileInfoType }
     * 
     * @return
     *     the new instance of {@link FileInfoType }
     */
    public FileInfoType createFileInfoType() {
        return new FileInfoType();
    }

    /**
     * Create an instance of {@link PhysicalDataObjectType }
     * 
     * @return
     *     the new instance of {@link PhysicalDataObjectType }
     */
    public PhysicalDataObjectType createPhysicalDataObjectType() {
        return new PhysicalDataObjectType();
    }

    /**
     * Create an instance of {@link CoreMetadataType }
     * 
     * @return
     *     the new instance of {@link CoreMetadataType }
     */
    public CoreMetadataType createCoreMetadataType() {
        return new CoreMetadataType();
    }

    /**
     * Create an instance of {@link DimensionsType }
     * 
     * @return
     *     the new instance of {@link DimensionsType }
     */
    public DimensionsType createDimensionsType() {
        return new DimensionsType();
    }

    /**
     * Create an instance of {@link MeasurementType }
     * 
     * @return
     *     the new instance of {@link MeasurementType }
     */
    public MeasurementType createMeasurementType() {
        return new MeasurementType();
    }

    /**
     * Create an instance of {@link MeasurementWeightType }
     * 
     * @return
     *     the new instance of {@link MeasurementWeightType }
     */
    public MeasurementWeightType createMeasurementWeightType() {
        return new MeasurementWeightType();
    }

    /**
     * Create an instance of {@link RuleIdType }
     * 
     * @return
     *     the new instance of {@link RuleIdType }
     */
    public RuleIdType createRuleIdType() {
        return new RuleIdType();
    }

    /**
     * Create an instance of {@link LogBookType }
     * 
     * @return
     *     the new instance of {@link LogBookType }
     */
    public LogBookType createLogBookType() {
        return new LogBookType();
    }

    /**
     * Create an instance of {@link AccessRuleType }
     * 
     * @return
     *     the new instance of {@link AccessRuleType }
     */
    public AccessRuleType createAccessRuleType() {
        return new AccessRuleType();
    }

    /**
     * Create an instance of {@link DisseminationRuleType }
     * 
     * @return
     *     the new instance of {@link DisseminationRuleType }
     */
    public DisseminationRuleType createDisseminationRuleType() {
        return new DisseminationRuleType();
    }

    /**
     * Create an instance of {@link ReuseRuleType }
     * 
     * @return
     *     the new instance of {@link ReuseRuleType }
     */
    public ReuseRuleType createReuseRuleType() {
        return new ReuseRuleType();
    }

    /**
     * Create an instance of {@link ClassificationRuleType }
     * 
     * @return
     *     the new instance of {@link ClassificationRuleType }
     */
    public ClassificationRuleType createClassificationRuleType() {
        return new ClassificationRuleType();
    }

    /**
     * Create an instance of {@link StorageRuleType }
     * 
     * @return
     *     the new instance of {@link StorageRuleType }
     */
    public StorageRuleType createStorageRuleType() {
        return new StorageRuleType();
    }

    /**
     * Create an instance of {@link AppraisalRuleType }
     * 
     * @return
     *     the new instance of {@link AppraisalRuleType }
     */
    public AppraisalRuleType createAppraisalRuleType() {
        return new AppraisalRuleType();
    }

    /**
     * Create an instance of {@link UpdateOperationType }
     * 
     * @return
     *     the new instance of {@link UpdateOperationType }
     */
    public UpdateOperationType createUpdateOperationType() {
        return new UpdateOperationType();
    }

    /**
     * Create an instance of {@link HoldRuleType }
     * 
     * @return
     *     the new instance of {@link HoldRuleType }
     */
    public HoldRuleType createHoldRuleType() {
        return new HoldRuleType();
    }

    /**
     * Create an instance of {@link ArchiveUnitIdentifierKeyType }
     * 
     * @return
     *     the new instance of {@link ArchiveUnitIdentifierKeyType }
     */
    public ArchiveUnitIdentifierKeyType createArchiveUnitIdentifierKeyType() {
        return new ArchiveUnitIdentifierKeyType();
    }

    /**
     * Create an instance of {@link ToDeleteType }
     * 
     * @return
     *     the new instance of {@link ToDeleteType }
     */
    public ToDeleteType createToDeleteType() {
        return new ToDeleteType();
    }

    /**
     * Create an instance of {@link ArchiveUnitType }
     * 
     * @return
     *     the new instance of {@link ArchiveUnitType }
     */
    public ArchiveUnitType createArchiveUnitType() {
        return new ArchiveUnitType();
    }

    /**
     * Create an instance of {@link ManagementType }
     * 
     * @return
     *     the new instance of {@link ManagementType }
     */
    public ManagementType createManagementType() {
        return new ManagementType();
    }

    /**
     * Create an instance of {@link ObjectGroupRefType }
     * 
     * @return
     *     the new instance of {@link ObjectGroupRefType }
     */
    public ObjectGroupRefType createObjectGroupRefType() {
        return new ObjectGroupRefType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType }
     * 
     * @return
     *     the new instance of {@link DescriptiveMetadataContentType }
     */
    public DescriptiveMetadataContentType createDescriptiveMetadataContentType() {
        return new DescriptiveMetadataContentType();
    }

    /**
     * Create an instance of {@link ManagementHistoryType }
     * 
     * @return
     *     the new instance of {@link ManagementHistoryType }
     */
    public ManagementHistoryType createManagementHistoryType() {
        return new ManagementHistoryType();
    }

    /**
     * Create an instance of {@link ManagementHistoryDataType }
     * 
     * @return
     *     the new instance of {@link ManagementHistoryDataType }
     */
    public ManagementHistoryDataType createManagementHistoryDataType() {
        return new ManagementHistoryDataType();
    }

    /**
     * Create an instance of {@link CodeListVersionsType }
     * 
     * @return
     *     the new instance of {@link CodeListVersionsType }
     */
    public CodeListVersionsType createCodeListVersionsType() {
        return new CodeListVersionsType();
    }

    /**
     * Create an instance of {@link DataObjectGroupType }
     * 
     * @return
     *     the new instance of {@link DataObjectGroupType }
     */
    public DataObjectGroupType createDataObjectGroupType() {
        return new DataObjectGroupType();
    }

    /**
     * Create an instance of {@link LogBookOgType }
     * 
     * @return
     *     the new instance of {@link LogBookOgType }
     */
    public LogBookOgType createLogBookOgType() {
        return new LogBookOgType();
    }

    /**
     * Create an instance of {@link EventLogBookOgType }
     * 
     * @return
     *     the new instance of {@link EventLogBookOgType }
     */
    public EventLogBookOgType createEventLogBookOgType() {
        return new EventLogBookOgType();
    }

    /**
     * Create an instance of {@link DataObjectPackageType }
     * 
     * @return
     *     the new instance of {@link DataObjectPackageType }
     */
    public DataObjectPackageType createDataObjectPackageType() {
        return new DataObjectPackageType();
    }

    /**
     * Create an instance of {@link ManagementMetadataType }
     * 
     * @return
     *     the new instance of {@link ManagementMetadataType }
     */
    public ManagementMetadataType createManagementMetadataType() {
        return new ManagementMetadataType();
    }

    /**
     * Create an instance of {@link AuthorizationRequestContentType }
     * 
     * @return
     *     the new instance of {@link AuthorizationRequestContentType }
     */
    public AuthorizationRequestContentType createAuthorizationRequestContentType() {
        return new AuthorizationRequestContentType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataType }
     * 
     * @return
     *     the new instance of {@link DescriptiveMetadataType }
     */
    public DescriptiveMetadataType createDescriptiveMetadataType() {
        return new DescriptiveMetadataType();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     * @return
     *     the new instance of {@link OperationType }
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link OrganizationWithIdType }
     * 
     * @return
     *     the new instance of {@link OrganizationWithIdType }
     */
    public OrganizationWithIdType createOrganizationWithIdType() {
        return new OrganizationWithIdType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ObjectGroupExtenstionAbstract")
    public JAXBElement<Object> createObjectGroupExtenstionAbstract(Object value) {
        return new JAXBElement<>(_ObjectGroupExtenstionAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "OtherDimensionsAbstract")
    public JAXBElement<Object> createOtherDimensionsAbstract(Object value) {
        return new JAXBElement<>(_OtherDimensionsAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OpenType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "OtherCoreTechnicalMetadataAbstract")
    public JAXBElement<OpenType> createOtherCoreTechnicalMetadataAbstract(OpenType value) {
        return new JAXBElement<>(_OtherCoreTechnicalMetadataAbstract_QNAME, OpenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveUnitReferenceAbstract")
    public JAXBElement<Object> createArchiveUnitReferenceAbstract(Object value) {
        return new JAXBElement<>(_ArchiveUnitReferenceAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "OtherManagementAbstract")
    public JAXBElement<Object> createOtherManagementAbstract(Object value) {
        return new JAXBElement<>(_OtherManagementAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "OtherCodeListAbstract")
    public JAXBElement<CodeType> createOtherCodeListAbstract(CodeType value) {
        return new JAXBElement<>(_OtherCodeListAbstract_QNAME, CodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "EventAbstract")
    public JAXBElement<Object> createEventAbstract(Object value) {
        return new JAXBElement<>(_EventAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AcknowledgementType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "Acknowledgement")
    public JAXBElement<AcknowledgementType> createAcknowledgement(AcknowledgementType value) {
        return new JAXBElement<>(_Acknowledgement_QNAME, AcknowledgementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveDeliveryRequest")
    public JAXBElement<ArchiveDeliveryRequestType> createArchiveDeliveryRequest(ArchiveDeliveryRequestType value) {
        return new JAXBElement<>(_ArchiveDeliveryRequest_QNAME, ArchiveDeliveryRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveRestitutionRequest")
    public JAXBElement<ArchiveRestitutionRequestType> createArchiveRestitutionRequest(ArchiveRestitutionRequestType value) {
        return new JAXBElement<>(_ArchiveRestitutionRequest_QNAME, ArchiveRestitutionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveTransferType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveTransfer")
    public JAXBElement<ArchiveTransferType> createArchiveTransfer(ArchiveTransferType value) {
        return new JAXBElement<>(_ArchiveTransfer_QNAME, ArchiveTransferType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveTransferRequest")
    public JAXBElement<ArchiveTransferRequestType> createArchiveTransferRequest(ArchiveTransferRequestType value) {
        return new JAXBElement<>(_ArchiveTransferRequest_QNAME, ArchiveTransferRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "AuthorizationControlAuthorityRequest")
    public JAXBElement<AuthorizationControlAuthorityRequestType> createAuthorizationControlAuthorityRequest(AuthorizationControlAuthorityRequestType value) {
        return new JAXBElement<>(_AuthorizationControlAuthorityRequest_QNAME, AuthorizationControlAuthorityRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "AuthorizationOriginatingAgencyRequest")
    public JAXBElement<AuthorizationOriginatingAgencyRequestType> createAuthorizationOriginatingAgencyRequest(AuthorizationOriginatingAgencyRequestType value) {
        return new JAXBElement<>(_AuthorizationOriginatingAgencyRequest_QNAME, AuthorizationOriginatingAgencyRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestReplyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestReplyType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveDeliveryRequestReply")
    public JAXBElement<ArchiveDeliveryRequestReplyType> createArchiveDeliveryRequestReply(ArchiveDeliveryRequestReplyType value) {
        return new JAXBElement<>(_ArchiveDeliveryRequestReply_QNAME, ArchiveDeliveryRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestReplyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestReplyType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveRestitutionRequestReply")
    public JAXBElement<ArchiveRestitutionRequestReplyType> createArchiveRestitutionRequestReply(ArchiveRestitutionRequestReplyType value) {
        return new JAXBElement<>(_ArchiveRestitutionRequestReply_QNAME, ArchiveRestitutionRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferReplyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveTransferReplyType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveTransferReply")
    public JAXBElement<ArchiveTransferReplyType> createArchiveTransferReply(ArchiveTransferReplyType value) {
        return new JAXBElement<>(_ArchiveTransferReply_QNAME, ArchiveTransferReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestReplyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestReplyType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveTransferRequestReply")
    public JAXBElement<ArchiveTransferRequestReplyType> createArchiveTransferRequestReply(ArchiveTransferRequestReplyType value) {
        return new JAXBElement<>(_ArchiveTransferRequestReply_QNAME, ArchiveTransferRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestReplyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestReplyType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "AuthorizationControlAuthorityRequestReply")
    public JAXBElement<AuthorizationControlAuthorityRequestReplyType> createAuthorizationControlAuthorityRequestReply(AuthorizationControlAuthorityRequestReplyType value) {
        return new JAXBElement<>(_AuthorizationControlAuthorityRequestReply_QNAME, AuthorizationControlAuthorityRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestReplyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestReplyType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "AuthorizationOriginatingAgencyRequestReply")
    public JAXBElement<AuthorizationOriginatingAgencyRequestReplyType> createAuthorizationOriginatingAgencyRequestReply(AuthorizationOriginatingAgencyRequestReplyType value) {
        return new JAXBElement<>(_AuthorizationOriginatingAgencyRequestReply_QNAME, AuthorizationOriginatingAgencyRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDestructionNotificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveDestructionNotificationType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveDestructionNotification")
    public JAXBElement<ArchiveDestructionNotificationType> createArchiveDestructionNotification(ArchiveDestructionNotificationType value) {
        return new JAXBElement<>(_ArchiveDestructionNotification_QNAME, ArchiveDestructionNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveModificationNotificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveModificationNotificationType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveModificationNotification")
    public JAXBElement<ArchiveModificationNotificationType> createArchiveModificationNotification(ArchiveModificationNotificationType value) {
        return new JAXBElement<>(_ArchiveModificationNotification_QNAME, ArchiveModificationNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveUnitType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArchiveUnitType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveUnit", scope = ArchiveUnitType.class)
    public JAXBElement<ArchiveUnitType> createArchiveUnitTypeArchiveUnit(ArchiveUnitType value) {
        return new JAXBElement<>(_ArchiveUnitTypeArchiveUnit_QNAME, ArchiveUnitType.class, ArchiveUnitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectRefType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataObjectRefType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "DataObjectReference", scope = ArchiveUnitType.class)
    public JAXBElement<DataObjectRefType> createArchiveUnitTypeDataObjectReference(DataObjectRefType value) {
        return new JAXBElement<>(_ArchiveUnitTypeDataObjectReference_QNAME, DataObjectRefType.class, ArchiveUnitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectGroupRefType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectGroupRefType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "DataObjectGroup", scope = ArchiveUnitType.class)
    public JAXBElement<ObjectGroupRefType> createArchiveUnitTypeDataObjectGroup(ObjectGroupRefType value) {
        return new JAXBElement<>(_ArchiveUnitTypeDataObjectGroup_QNAME, ObjectGroupRefType.class, ArchiveUnitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "ArchiveUnitRefId", scope = ToDeleteType.class)
    @XmlIDREF
    public JAXBElement<Object> createToDeleteTypeArchiveUnitRefId(Object value) {
        return new JAXBElement<>(_ToDeleteTypeArchiveUnitRefId_QNAME, Object.class, ToDeleteType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleIdType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RuleIdType }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "Rule", scope = HoldRuleType.class)
    public JAXBElement<RuleIdType> createHoldRuleTypeRule(RuleIdType value) {
        return new JAXBElement<>(_HoldRuleTypeRule_QNAME, RuleIdType.class, HoldRuleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "StartDate", scope = HoldRuleType.class)
    public JAXBElement<XMLGregorianCalendar> createHoldRuleTypeStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<>(_HoldRuleTypeStartDate_QNAME, XMLGregorianCalendar.class, HoldRuleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "HoldEndDate", scope = HoldRuleType.class)
    public JAXBElement<XMLGregorianCalendar> createHoldRuleTypeHoldEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<>(_HoldRuleTypeHoldEndDate_QNAME, XMLGregorianCalendar.class, HoldRuleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "HoldOwner", scope = HoldRuleType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHoldRuleTypeHoldOwner(String value) {
        return new JAXBElement<>(_HoldRuleTypeHoldOwner_QNAME, String.class, HoldRuleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "HoldReassessingDate", scope = HoldRuleType.class)
    public JAXBElement<XMLGregorianCalendar> createHoldRuleTypeHoldReassessingDate(XMLGregorianCalendar value) {
        return new JAXBElement<>(_HoldRuleTypeHoldReassessingDate_QNAME, XMLGregorianCalendar.class, HoldRuleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "HoldReason", scope = HoldRuleType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHoldRuleTypeHoldReason(String value) {
        return new JAXBElement<>(_HoldRuleTypeHoldReason_QNAME, String.class, HoldRuleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2", name = "PreventRearrangement", scope = HoldRuleType.class)
    public JAXBElement<Boolean> createHoldRuleTypePreventRearrangement(Boolean value) {
        return new JAXBElement<>(_HoldRuleTypePreventRearrangement_QNAME, Boolean.class, HoldRuleType.class, value);
    }

}
