//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrganizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="OrganizationType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Identifier" type="{fr:gouv:culture:archivesdefrance:seda:v2}IdentifierType"/>
 *         <element name="OrganizationDescriptiveMetadata" type="{fr:gouv:culture:archivesdefrance:seda:v2}OrganizationDescriptiveMetadataType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationType", propOrder = {
    "identifier",
    "organizationDescriptiveMetadata"
})
@XmlSeeAlso({
    OrganizationWithIdType.class
})
public class OrganizationType {

    @XmlElement(name = "Identifier", required = true)
    protected IdentifierType identifier;
    @XmlElement(name = "OrganizationDescriptiveMetadata")
    protected OrganizationDescriptiveMetadataType organizationDescriptiveMetadata;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the organizationDescriptiveMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationDescriptiveMetadataType }
     *     
     */
    public OrganizationDescriptiveMetadataType getOrganizationDescriptiveMetadata() {
        return organizationDescriptiveMetadata;
    }

    /**
     * Sets the value of the organizationDescriptiveMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationDescriptiveMetadataType }
     *     
     */
    public void setOrganizationDescriptiveMetadata(OrganizationDescriptiveMetadataType value) {
        this.organizationDescriptiveMetadata = value;
    }

}
