//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.29 at 01:17:12 AM CET 
//
package fr.gouv.culture.archivesdefrance.seda.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OrganizationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrganizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifier" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType"/>
 *         &lt;element name="OrganizationDescriptiveMetadata" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}OrganizationDescriptiveMetadataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationType", propOrder = {
    "identifier",
    "organizationDescriptiveMetadata"
})
@XmlSeeAlso({
    OrganizationWithIdType.class
})
public class OrganizationType {

    /**
     * The Identifier.
     */
    @XmlElement(name = "Identifier", required = true)
    protected IdentifierType identifier;
    /**
     * The Organization descriptive metadata.
     */
    @XmlElement(name = "OrganizationDescriptiveMetadata")
    protected OrganizationDescriptiveMetadataType organizationDescriptiveMetadata;

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is {@link IdentifierType }
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is {@link IdentifierType }
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the organizationDescriptiveMetadata property.
     *
     * @return possible object is {@link OrganizationDescriptiveMetadataType }
     */
    public OrganizationDescriptiveMetadataType getOrganizationDescriptiveMetadata() {
        return organizationDescriptiveMetadata;
    }

    /**
     * Sets the value of the organizationDescriptiveMetadata property.
     *
     * @param value allowed object is {@link OrganizationDescriptiveMetadataType
     *              }
     */
    public void setOrganizationDescriptiveMetadata(OrganizationDescriptiveMetadataType value) {
        this.organizationDescriptiveMetadata = value;
    }

}
