//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="SignatureType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Signer" type="{fr:gouv:culture:archivesdefrance:seda:v2}SignerType" maxOccurs="unbounded"/>
 *         <element name="Validator" type="{fr:gouv:culture:archivesdefrance:seda:v2}ValidatorType"/>
 *         <element name="Masterdata" type="{fr:gouv:culture:archivesdefrance:seda:v2}CodeType" minOccurs="0"/>
 *         <element name="ReferencedObject" type="{fr:gouv:culture:archivesdefrance:seda:v2}ReferencedObjectType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureType", propOrder = {
    "signer",
    "validator",
    "masterdata",
    "referencedObject"
})
public class SignatureType {

    @XmlElement(name = "Signer", required = true)
    protected List<SignerType> signer;
    @XmlElement(name = "Validator", required = true)
    protected ValidatorType validator;
    @XmlElement(name = "Masterdata")
    protected CodeType masterdata;
    @XmlElement(name = "ReferencedObject", required = true)
    protected ReferencedObjectType referencedObject;

    /**
     * Gets the value of the signer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the signer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSigner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignerType }
     * 
     * 
     * @return
     *     The value of the signer property.
     */
    public List<SignerType> getSigner() {
        if (signer == null) {
            signer = new ArrayList<>();
        }
        return this.signer;
    }

    /**
     * Gets the value of the validator property.
     * 
     * @return
     *     possible object is
     *     {@link ValidatorType }
     *     
     */
    public ValidatorType getValidator() {
        return validator;
    }

    /**
     * Sets the value of the validator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidatorType }
     *     
     */
    public void setValidator(ValidatorType value) {
        this.validator = value;
    }

    /**
     * Gets the value of the masterdata property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getMasterdata() {
        return masterdata;
    }

    /**
     * Sets the value of the masterdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setMasterdata(CodeType value) {
        this.masterdata = value;
    }

    /**
     * Gets the value of the referencedObject property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedObjectType }
     *     
     */
    public ReferencedObjectType getReferencedObject() {
        return referencedObject;
    }

    /**
     * Sets the value of the referencedObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedObjectType }
     *     
     */
    public void setReferencedObject(ReferencedObjectType value) {
        this.referencedObject = value;
    }

}
