//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package fr.gouv.culture.archivesdefrance.seda.v22;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for EventLogBookOgType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="EventLogBookOgType">
 *   <complexContent>
 *     <extension base="{fr:gouv:culture:archivesdefrance:seda:v2.2}EventType">
 *       <sequence>
 *         <element name="DataObjectReferenceId" type="{fr:gouv:culture:archivesdefrance:seda:v2.2}DataObjectRefIdType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "EventLogBookOgType",
    propOrder = {"dataObjectReferenceId"})
public class EventLogBookOgType extends EventType {

  /**
   * Permet de faire référence à un objet-donnée binaire ou physique déjà présent dans les
   * métadonnées du bordereau.
   */
  @XmlElement(name = "DataObjectReferenceId")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object dataObjectReferenceId;

  /**
   * Permet de faire référence à un objet-donnée binaire ou physique déjà présent dans les
   * métadonnées du bordereau.
   *
   * @return possible object is {@link Object }
   */
  public Object getDataObjectReferenceId() {
    return dataObjectReferenceId;
  }

  /**
   * Sets the value of the dataObjectReferenceId property.
   *
   * @param value allowed object is {@link Object }
   * @see #getDataObjectReferenceId()
   */
  public void setDataObjectReferenceId(Object value) {
    this.dataObjectReferenceId = value;
  }
}
