//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.15 at 09:28:44 PM CET 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinalActionAppraisalCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FinalActionAppraisalCodeType">
 *   &lt;restriction base="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType">
 *     &lt;enumeration value="Keep"/>
 *     &lt;enumeration value="Destroy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FinalActionAppraisalCodeType")
@XmlEnum
public enum FinalActionAppraisalCodeType {

    @XmlEnumValue("Keep")
    KEEP("Keep"),
    @XmlEnumValue("Destroy")
    DESTROY("Destroy");
    private final String value;

    FinalActionAppraisalCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FinalActionAppraisalCodeType fromValue(String v) {
        for (FinalActionAppraisalCodeType c: FinalActionAppraisalCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
