//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.15 at 09:28:44 PM CET 
//


package fr.gouv.culture.archivesdefrance.seda.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedObjectReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedObjectReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsVersionOf" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Replaces" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Requires" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IsPartOf" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="References" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedObjectReferenceType", propOrder = {
    "isVersionOf",
    "replaces",
    "requires",
    "isPartOf",
    "references"
})
public class RelatedObjectReferenceType {

    @XmlElement(name = "IsVersionOf")
    protected List<DataObjectOrArchiveUnitReferenceType> isVersionOf;
    @XmlElement(name = "Replaces")
    protected List<DataObjectOrArchiveUnitReferenceType> replaces;
    @XmlElement(name = "Requires")
    protected List<DataObjectOrArchiveUnitReferenceType> requires;
    @XmlElement(name = "IsPartOf")
    protected List<DataObjectOrArchiveUnitReferenceType> isPartOf;
    @XmlElement(name = "References")
    protected List<DataObjectOrArchiveUnitReferenceType> references;

    /**
     * Gets the value of the isVersionOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isVersionOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsVersionOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObjectOrArchiveUnitReferenceType }
     * 
     * 
     */
    public List<DataObjectOrArchiveUnitReferenceType> getIsVersionOf() {
        if (isVersionOf == null) {
            isVersionOf = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
        }
        return this.isVersionOf;
    }

    /**
     * Gets the value of the replaces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replaces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplaces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObjectOrArchiveUnitReferenceType }
     * 
     * 
     */
    public List<DataObjectOrArchiveUnitReferenceType> getReplaces() {
        if (replaces == null) {
            replaces = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
        }
        return this.replaces;
    }

    /**
     * Gets the value of the requires property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requires property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequires().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObjectOrArchiveUnitReferenceType }
     * 
     * 
     */
    public List<DataObjectOrArchiveUnitReferenceType> getRequires() {
        if (requires == null) {
            requires = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
        }
        return this.requires;
    }

    /**
     * Gets the value of the isPartOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isPartOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsPartOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObjectOrArchiveUnitReferenceType }
     * 
     * 
     */
    public List<DataObjectOrArchiveUnitReferenceType> getIsPartOf() {
        if (isPartOf == null) {
            isPartOf = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
        }
        return this.isPartOf;
    }

    /**
     * Gets the value of the references property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the references property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObjectOrArchiveUnitReferenceType }
     * 
     * 
     */
    public List<DataObjectOrArchiveUnitReferenceType> getReferences() {
        if (references == null) {
            references = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
        }
        return this.references;
    }

}
