//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.15 at 07:07:47 PM CEST 
//
package org.w3._1999.xlink;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for actuateType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="actuateType"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"> &lt;enumeration
 * value="onLoad"/> &lt;enumeration value="onRequest"/> &lt;enumeration value="other"/> &lt;enumeration value="none"/>
 * &lt;/restriction> &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "actuateType")
@XmlEnum
public enum ActuateType {

    /**
     * On load actuate type.
     */
    @XmlEnumValue("onLoad")
    ON_LOAD("onLoad"),
    /**
     * On request actuate type.
     */
    @XmlEnumValue("onRequest")
    ON_REQUEST("onRequest"),
    /**
     * Other actuate type.
     */
    @XmlEnumValue("other")
    OTHER("other"),
    /**
     * None actuate type.
     */
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    ActuateType(String v) {
        value = v;
    }

    /**
     * Value string.
     *
     * @return the string
     */
    public String value() {
        return value;
    }

    /**
     * From value actuate type.
     *
     * @param v the v
     * @return the actuate type
     */
    public static ActuateType fromValue(String v) {
        for (ActuateType c : ActuateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
