//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package fr.gouv.culture.archivesdefrance.seda.v23;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Référence à un objet-données ou à un groupe d'objets-données.
 *
 * <p>Java class for DataObjectRefType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="DataObjectRefType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice>
 *           <element name="DataObjectReferenceId" type="{fr:gouv:culture:archivesdefrance:seda:v2.3}DataObjectRefIdType"/>
 *           <element name="DataObjectGroupReferenceId" type="{fr:gouv:culture:archivesdefrance:seda:v2.3}GroupRefIdType"/>
 *         </choice>
 *       </sequence>
 *       <attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "DataObjectRefType",
    propOrder = {"dataObjectReferenceId", "dataObjectGroupReferenceId"})
@XmlRootElement(name = "DataObjectReference")
public class DataObjectRefType {

  /** Référence à un objet-données listé dans les métadonnées de transport. */
  @XmlElement(name = "DataObjectReferenceId")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object dataObjectReferenceId;

  /** Référence à un groupe d'objets-données listé dans les métadonnées de transport. */
  @XmlElement(name = "DataObjectGroupReferenceId")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object dataObjectGroupReferenceId;

  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  /**
   * Référence à un objet-données listé dans les métadonnées de transport.
   *
   * @return possible object is {@link Object }
   */
  public Object getDataObjectReferenceId() {
    return dataObjectReferenceId;
  }

  /**
   * Sets the value of the dataObjectReferenceId property.
   *
   * @param value allowed object is {@link Object }
   * @see #getDataObjectReferenceId()
   */
  public void setDataObjectReferenceId(Object value) {
    this.dataObjectReferenceId = value;
  }

  /**
   * Référence à un groupe d'objets-données listé dans les métadonnées de transport.
   *
   * @return possible object is {@link Object }
   */
  public Object getDataObjectGroupReferenceId() {
    return dataObjectGroupReferenceId;
  }

  /**
   * Sets the value of the dataObjectGroupReferenceId property.
   *
   * @param value allowed object is {@link Object }
   * @see #getDataObjectGroupReferenceId()
   */
  public void setDataObjectGroupReferenceId(Object value) {
    this.dataObjectGroupReferenceId = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }
}
