name: Deploy on github

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Deploy
      run: mvn -B -Pgithub deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
