name: Deploy on github

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Deploy
      run: mvn -B -Pgithub deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
