name: Maven deploy on github

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Deploy
      run: mvn -B -Pgithub deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
